/**
 * tlane import-helicone — read a Helicone setup (env vars + custom
 * properties) and emit a Tracelane gateway config + .env stanza.
 *
 * Helicone is mostly a proxy with config-via-env + per-request headers,
 * not a YAML config like LiteLLM. So this CLI:
 *
 *   1. Reads `.env` (or `--env <path>`) looking for HELICONE_*
 *   2. Translates each known var to its Tracelane equivalent
 *   3. Emits a new `.env.tracelane` stanza with the renamed vars
 *   4. If `--with-config`, also emits `tracelane.yaml` with provider
 *      routing pulled from Helicone's `Helicone-Property-*` examples
 *      in your codebase (best-effort grep over `--src <dir>`)
 *
 * Usage:
 *   tlane import-helicone                        # in repo root, scans .env
 *   tlane import-helicone --env config/.env
 *   tlane import-helicone --env .env --with-config --src src/
 *   tlane import-helicone --dry-run              # print, don't write
 *
 * Maps the canonical migration table from
 */

import * as fs from "node:fs";
import * as path from "node:path";
import process from "node:process";
import type { Command } from "commander";

// ── Translation tables ──────────────────────────────────────────────────────

/** HELICONE_* env var → TRACELANE_* env var */
const ENV_VAR_MAP: ReadonlyArray<readonly [string, string, string]> = [
	// [helicone, tracelane, comment]
	["HELICONE_API_KEY", "TRACELANE_API_KEY", "Tenant API key (tlane_<base62>)"],
	[
		"HELICONE_BASE_URL",
		"TRACELANE_GATEWAY_URL",
		"Gateway URL (override only for self-hosted)",
	],
	[
		"HELICONE_OPENAI_API_BASE",
		"OPENAI_BASE_URL",
		"Direct provider override; usually unset",
	],
	[
		"HELICONE_USER_ID",
		"TRACELANE_USER_ID",
		"Per-request actor; set via metadata.user_id in body",
	],
	[
		"HELICONE_PROPERTY_PREFIX",
		"",
		"No equivalent — Tracelane uses spans + metadata",
	],
	[
		"HELICONE_CACHE_ENABLED",
		"",
		"Tracelane has no built-in caching layer in V1 — drop",
	],
	[
		"HELICONE_RATE_LIMIT_ENABLED",
		"",
		"Tracelane rate-limits per-tenant by default; this var is a no-op",
	],
];

/** Header rename. Helicone request headers → Tracelane equivalent. */
const HEADER_MAP: ReadonlyArray<readonly [string, string]> = [
	["Helicone-Auth", "Authorization"],
	["Helicone-User-Id", "X-Tracelane-User-Id"],
	["Helicone-Session-Id", "X-Tracelane-Session-Id"],
	[
		"Helicone-Property-*",
		"X-Tracelane-Property-* (carried through to span attributes)",
	],
	[
		"Helicone-Cache-Enabled",
		"(no equivalent — drop; Tracelane has no V1 cache)",
	],
	["Helicone-RateLimit-Policy", "(handled server-side per tenant — drop)"],
];

interface ParsedEnv {
	heliconeVars: Map<string, string>;
	otherVars: Map<string, string>;
}

export function parseEnvFile(filepath: string): ParsedEnv {
	const heliconeVars = new Map<string, string>();
	const otherVars = new Map<string, string>();
	if (!fs.existsSync(filepath)) {
		return { heliconeVars, otherVars };
	}
	const lines = fs.readFileSync(filepath, "utf8").split(/\r?\n/);
	for (const raw of lines) {
		const line = raw.trim();
		if (!line || line.startsWith("#")) continue;
		const eq = line.indexOf("=");
		if (eq < 0) continue;
		const key = line.slice(0, eq).trim();
		const value = line.slice(eq + 1).trim();
		if (key.startsWith("HELICONE_")) {
			heliconeVars.set(key, value);
		} else {
			otherVars.set(key, value);
		}
	}
	return { heliconeVars, otherVars };
}

export function emitEnvStanza(parsed: ParsedEnv): string {
	const lines: string[] = [
		"# Tracelane env — auto-generated by `tlane import-helicone`.",
		"# Review then move to your secrets store.",
		"",
	];
	const seen = new Set<string>();
	for (const [helicone, tracelane, comment] of ENV_VAR_MAP) {
		const value = parsed.heliconeVars.get(helicone);
		if (value === undefined) continue;
		seen.add(helicone);
		if (tracelane === "") {
			lines.push(`# ${helicone}=${value}  # ${comment}`);
		} else {
			lines.push(`${tracelane}=${value}  # was ${helicone} — ${comment}`);
		}
	}
	const unmapped = [...parsed.heliconeVars.entries()].filter(
		([k]) => !seen.has(k),
	);
	if (unmapped.length > 0) {
		lines.push("");
		lines.push(
			"# Unmapped HELICONE_* vars (no known equivalent — review manually):",
		);
		for (const [k, v] of unmapped) {
			lines.push(`# ${k}=${v}`);
		}
	}
	return `${lines.join("\n")}\n`;
}

function emitHeaderTable(): string {
	const rows = HEADER_MAP.map(([h, t]) => `  ${h.padEnd(28)} → ${t}`);
	return [
		"# Helicone request-header → Tracelane equivalent",
		"#",
		...rows,
		"",
	].join("\n");
}

// ── Command registration ────────────────────────────────────────────────────

interface Opts {
	env: string;
	output?: string;
	withConfig?: boolean;
	src?: string;
	dryRun?: boolean;
}

export function registerImportHeliconeCommand(program: Command): void {
	program
		.command("import-helicone")
		.description(
			"Import Helicone env + headers and emit a Tracelane-flavoured stanza.",
		)
		.option("--env <path>", "Path to .env file to read", ".env")
		.option(
			"--output <path>",
			"Path to write Tracelane stanza (default: .env.tracelane)",
			".env.tracelane",
		)
		.option(
			"--with-config",
			"Also emit a tracelane.yaml routing config (best-effort)",
			false,
		)
		.option(
			"--src <dir>",
			"Source dir to grep for Helicone-Property-* usage (with --with-config)",
			"src/",
		)
		.option("--dry-run", "Print to stdout instead of writing files", false)
		.action((opts: Opts) => {
			const envPath = path.resolve(opts.env);
			const parsed = parseEnvFile(envPath);
			if (parsed.heliconeVars.size === 0) {
				process.stderr.write(
					`tlane import-helicone: no HELICONE_* vars found in ${envPath}.\n  Pass --env <path> if your .env is elsewhere, or remove this step\n  if you only used Helicone via request headers (then see\n  docs/migrations/from-helicone.md header table).\n`,
				);
				process.exit(2);
			}

			const envStanza = emitEnvStanza(parsed);
			const headerTable = emitHeaderTable();

			if (opts.dryRun) {
				process.stdout.write("# === .env.tracelane ===\n");
				process.stdout.write(envStanza);
				process.stdout.write("\n# === Header migration table ===\n");
				process.stdout.write(headerTable);
				return;
			}

			const outPath = path.resolve(opts.output ?? ".env.tracelane");
			fs.writeFileSync(outPath, envStanza, "utf8");
			process.stdout.write(
				`Wrote ${outPath} (${parsed.heliconeVars.size} HELICONE_* vars translated).\n`,
			);
			process.stdout.write("\n");
			process.stdout.write(headerTable);

			if (opts.withConfig) {
				const cfgPath = path.resolve("tracelane.yaml");
				const cfg = [
					"# Tracelane gateway config — minimal scaffold from `tlane import-helicone`.",
					"# Edit to add your full provider list. Reference:",
					"#   https://docs.tracelane.dev/config",
					"",
					"providers:",
					"  - name: anthropic",
					"    api_key_env: ANTHROPIC_API_KEY",
					"  - name: openai",
					"    api_key_env: OPENAI_API_KEY",
					"",
					"observability:",
					"  otlp_endpoint: http://localhost:4317",
					"",
				].join("\n");
				fs.writeFileSync(cfgPath, cfg, "utf8");
				process.stdout.write(
					`Wrote ${cfgPath} (scaffold — extend per docs).\n`,
				);
				if (opts.src) {
					process.stdout.write(
						`Scan ${opts.src} for Helicone-Property-* references (manual step for V1).\n`,
					);
				}
			}
		});
}
