/**
 * tlane import-helicone — rename a Helicone `.env` into its Tracelane
 * equivalent, or import saved historical request JSON with --traces <path>.
 * Historical imports use OTLP and a resumable local cursor.
 *
 * Helicone is mostly a proxy with config-via-env + per-request headers,
 * not a YAML config like LiteLLM. So this CLI:
 *
 *   1. Reads `.env` (or `--env <path>`) looking for HELICONE_*
 *   2. Translates each known var to its Tracelane equivalent
 *   3. Emits a new `.env.tracelane` stanza with the renamed vars
 *   4. Prints the Helicone → Tracelane request-header rename table
 *   5. If `--with-config`, writes a fixed two-provider `tracelane.yaml`
 *      starter scaffold to edit — it is not derived from your codebase
 *
 * Usage:
 *   tlane import-helicone                        # in repo root, scans .env
 *   tlane import-helicone --env config/.env
 *   tlane import-helicone --env .env --with-config
 *   tlane import-helicone --dry-run              # print, don't write
 *
 * Maps the canonical migration table from
 * docs/migrations/from-helicone.md.
 */

import { createHash } from "node:crypto";
import * as fs from "node:fs";
import * as path from "node:path";
import process from "node:process";
import type { Command } from "commander";

// ── Translation tables ──────────────────────────────────────────────────────

/** HELICONE_* env var → TRACELANE_* env var */
const ENV_VAR_MAP: ReadonlyArray<readonly [string, string, string]> = [
	// [helicone, tracelane, comment]
	["HELICONE_API_KEY", "TRACELANE_API_KEY", "Tenant API key (tlane_<base62>)"],
	[
		"HELICONE_BASE_URL",
		"TRACELANE_GATEWAY_URL",
		"Gateway URL (override only for self-hosted)",
	],
	[
		"HELICONE_OPENAI_API_BASE",
		"OPENAI_BASE_URL",
		"Direct provider override; usually unset",
	],
	[
		"HELICONE_USER_ID",
		"",
		"Not an env var — send the X-Tracelane-User-Id header (or OpenAI's `user` field) per request",
	],
	[
		"HELICONE_PROPERTY_PREFIX",
		"",
		"No equivalent — Tracelane has no custom-property header",
	],
	[
		"HELICONE_CACHE_ENABLED",
		"",
		"Not a client toggle — Tracelane's response cache is operator-configured; drop",
	],
	[
		"HELICONE_RATE_LIMIT_ENABLED",
		"",
		"Tracelane rate-limits per-tenant by default; this var is a no-op",
	],
];

/** Header rename. Helicone request headers → Tracelane equivalent. */
const HEADER_MAP: ReadonlyArray<readonly [string, string]> = [
	["Helicone-Auth", "Authorization"],
	["Helicone-User-Id", "X-Tracelane-User-Id"],
	["Helicone-Session-Id", "X-Conversation-Id (X-Session-Id also accepted)"],
	[
		"Helicone-Property-*",
		"(no equivalent — drop; nearest is the single X-Business-Reference)",
	],
	[
		"Helicone-Cache-Enabled",
		"(no equivalent — the response cache is operator-configured, not per-request)",
	],
	["Helicone-RateLimit-Policy", "(handled server-side per tenant — drop)"],
];

interface ParsedEnv {
	heliconeVars: Map<string, string>;
	otherVars: Map<string, string>;
}

export function parseEnvFile(filepath: string): ParsedEnv {
	const heliconeVars = new Map<string, string>();
	const otherVars = new Map<string, string>();
	if (!fs.existsSync(filepath)) {
		return { heliconeVars, otherVars };
	}
	const lines = fs.readFileSync(filepath, "utf8").split(/\r?\n/);
	for (const raw of lines) {
		const line = raw.trim();
		if (!line || line.startsWith("#")) continue;
		const eq = line.indexOf("=");
		if (eq < 0) continue;
		const key = line.slice(0, eq).trim();
		const value = line.slice(eq + 1).trim();
		if (key.startsWith("HELICONE_")) {
			heliconeVars.set(key, value);
		} else {
			otherVars.set(key, value);
		}
	}
	return { heliconeVars, otherVars };
}

export function emitEnvStanza(parsed: ParsedEnv): string {
	const lines: string[] = [
		"# Tracelane env — auto-generated by `tlane import-helicone`.",
		"# Review then move to your secrets store.",
		"",
	];
	const seen = new Set<string>();
	for (const [helicone, tracelane, comment] of ENV_VAR_MAP) {
		const value = parsed.heliconeVars.get(helicone);
		if (value === undefined) continue;
		seen.add(helicone);
		if (tracelane === "") {
			lines.push(`# ${helicone}=${value}  # ${comment}`);
		} else {
			lines.push(`${tracelane}=${value}  # was ${helicone} — ${comment}`);
		}
	}
	const unmapped = [...parsed.heliconeVars.entries()].filter(
		([k]) => !seen.has(k),
	);
	if (unmapped.length > 0) {
		lines.push("");
		lines.push(
			"# Unmapped HELICONE_* vars (no known equivalent — review manually):",
		);
		for (const [k, v] of unmapped) {
			lines.push(`# ${k}=${v}`);
		}
	}
	return `${lines.join("\n")}\n`;
}

function emitHeaderTable(): string {
	const rows = HEADER_MAP.map(([h, t]) => `  ${h.padEnd(28)} → ${t}`);
	return [
		"# Helicone request-header → Tracelane equivalent",
		"#",
		...rows,
		"",
	].join("\n");
}

// Historical request import uses the documented Helicone request JSON fields.
// https://docs.helicone.ai/rest/request/get-v1request
export interface TraceImportOptions {
	traces: string;
	cursor: string;
	endpoint: string;
	apiKey: string;
	dryRun?: boolean;
}

interface ImportCounts {
	imported: number;
	skipped: number;
	reasons: Record<string, number>;
}

type JsonRecord = Record<string, unknown>;
function record(value: unknown): value is JsonRecord {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

function timestampNanos(value: unknown): bigint | undefined {
	if (typeof value !== "string") return undefined;
	const match =
		/^(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2})(?:\.(\d{1,9}))?(Z|[+-]\d{2}:\d{2})$/.exec(
			value,
		);
	if (!match) return undefined;
	const millis = Date.parse(`${match[1]}${match[3]}`);
	if (!Number.isSafeInteger(millis) || millis < 0) return undefined;
	const nanos =
		BigInt(millis) * 1000000n + BigInt((match[2] ?? "").padEnd(9, "0"));
	return nanos <= 0xffffffffffffffffn ? nanos : undefined;
}

function requestSpan(value: unknown): {
	span?: JsonRecord;
	reason?: string;
	id?: string;
} {
	if (
		!record(value) ||
		typeof value.request_id !== "string" ||
		!value.request_id.trim()
	)
		return { reason: "missing_request_id" };
	const id = value.request_id;
	const start = timestampNanos(value.request_created_at);
	let end = timestampNanos(value.response_created_at);
	if (
		value.response_created_at == null &&
		start !== undefined &&
		typeof value.delay_ms === "number" &&
		value.delay_ms >= 0
	) {
		const durationNanos = Math.round(value.delay_ms * 1000000);
		if (Number.isSafeInteger(durationNanos))
			end = start + BigInt(durationNanos);
	}
	if (
		start === undefined ||
		end === undefined ||
		end < start ||
		end > 0xffffffffffffffffn
	)
		return { id, reason: "invalid_timestamp" };
	const attributes: JsonRecord[] = [
		{
			key: "tracelane.business_reference",
			value: { stringValue: `helicone:${id}` },
		},
	];
	for (const [source, target] of [
		["provider", "gen_ai.provider.name"],
		["request_model", "gen_ai.request.model"],
		["response_model", "gen_ai.response.model"],
	] as const) {
		const item = value[source];
		if (typeof item === "string")
			attributes.push({
				key: target,
				value: {
					stringValue: source === "provider" ? item.toLowerCase() : item,
				},
			});
	}
	for (const [source, target] of [
		["prompt_tokens", "gen_ai.usage.input_tokens"],
		["completion_tokens", "gen_ai.usage.output_tokens"],
	] as const) {
		const item = value[source];
		if (item == null) continue;
		if (
			typeof item !== "number" ||
			!Number.isSafeInteger(item) ||
			item < 0 ||
			item > 0xffffffff
		)
			return { id, reason: "invalid_tokens" };
		attributes.push({ key: target, value: { intValue: String(item) } });
	}
	for (const [source, target] of [
		["request_body", "gen_ai.input.messages"],
		["response_body", "gen_ai.output.messages"],
	] as const) {
		if (value[source] != null)
			attributes.push({
				key: target,
				// Preserve the original JSON payload as a text part; do not guess
				// provider-specific message/tool schemas or fabricate a span tree.
				value: {
					stringValue: JSON.stringify([
						{
							role: source === "request_body" ? "user" : "assistant",
							parts: [{ type: "text", content: JSON.stringify(value[source]) }],
						},
					]),
				},
			});
	}
	const status = value.response_status;
	if (
		status != null &&
		(typeof status !== "number" ||
			!Number.isInteger(status) ||
			status < 100 ||
			status > 599)
	)
		return { id, reason: "invalid_status" };
	if (typeof status === "number")
		attributes.push({
			key: "http.response.status_code",
			value: { intValue: String(status) },
		});
	// Stable IDs survive an acknowledgement lost before the cursor is written.
	const hash = createHash("sha256")
		.update(`helicone:request:${id}`)
		.digest("hex");
	return {
		id,
		span: {
			traceId: hash.slice(0, 32),
			spanId: hash.slice(32, 48),
			name: "helicone.request",
			kind: 3,
			startTimeUnixNano: String(start),
			endTimeUnixNano: String(end),
			attributes,
			status: {
				code: typeof status === "number" ? (status >= 400 ? 2 : 1) : 0,
			},
		},
	};
}

export async function importHeliconeTraces(
	opts: TraceImportOptions,
): Promise<ImportCounts> {
	const destination = new URL(opts.endpoint);
	if (
		destination.username ||
		destination.password ||
		destination.search ||
		destination.hash ||
		!["", "/"].includes(destination.pathname)
	)
		throw new Error(
			"endpoint must be a gateway origin without credentials, path, query or fragment",
		);
	if (
		destination.protocol !== "https:" &&
		!(
			destination.protocol === "http:" &&
			["localhost", "127.0.0.1", "[::1]"].includes(destination.hostname)
		)
	)
		throw new Error("endpoint requires HTTPS (HTTP allowed only on loopback)");
	if (!opts.apiKey)
		throw new Error("Set TRACELANE_API_KEY to the destination workspace key");
	if (path.resolve(opts.traces) === path.resolve(opts.cursor))
		throw new Error("cursor must not overwrite the source export");
	const bytes = fs.readFileSync(opts.traces);
	let parsed: unknown;
	try {
		parsed = JSON.parse(bytes.toString("utf8"));
	} catch {
		throw new Error("Helicone export is not valid JSON");
	}
	const requests = Array.isArray(parsed)
		? parsed
		: record(parsed) && parsed.error == null && Array.isArray(parsed.data)
			? parsed.data
			: null;
	if (!requests)
		throw new Error(
			"Helicone export must be a request array or a successful {data: [...], error: null} response",
		);
	const fingerprint = createHash("sha256")
		.update(bytes)
		.update("\0")
		.update(destination.origin)
		.update("\0")
		.update(opts.apiKey)
		.digest("hex");
	let lock: number | undefined;
	try {
		if (!opts.dryRun) {
			try {
				lock = fs.openSync(`${opts.cursor}.lock`, "wx", 0o600);
			} catch {
				throw new Error(
					"Cannot acquire cursor lock; another import may be running. Check before removing a stale .lock file.",
				);
			}
		}
		let next = 0;
		if (fs.existsSync(opts.cursor)) {
			let saved: unknown;
			try {
				saved = JSON.parse(fs.readFileSync(opts.cursor, "utf8"));
			} catch {
				throw new Error("cursor is not valid JSON");
			}
			if (
				!record(saved) ||
				saved.version !== 1 ||
				saved.fingerprint !== fingerprint ||
				typeof saved.next !== "number" ||
				!Number.isSafeInteger(saved.next) ||
				saved.next < 0 ||
				saved.next > requests.length
			)
				throw new Error(
					"cursor does not match source, destination or key, or is invalid; use the original inputs or a separate cursor",
				);
			next = saved.next;
		}
		const counts: ImportCounts = {
			imported: 0,
			skipped: next,
			reasons: next ? { already_processed: next } : {},
		};
		const seen = new Set<string>();
		// Reconstruct duplicate IDs from the immutable prefix; no history lives in the cursor.
		for (let i = 0; i < next; i++) {
			const prior = requestSpan(requests[i]);
			if (prior.span && prior.id) seen.add(prior.id);
		}
		for (let i = next; i < requests.length; i++) {
			const converted = requestSpan(requests[i]);
			const reason =
				converted.reason ??
				(converted.id && seen.has(converted.id)
					? "duplicate_request_id"
					: undefined);
			if (reason) {
				counts.skipped++;
				counts.reasons[reason] = (counts.reasons[reason] ?? 0) + 1;
			} else {
				if (!opts.dryRun) {
					let response: Response;
					try {
						response = await fetch(`${destination.origin}/v1/traces`, {
							method: "POST",
							headers: {
								"Content-Type": "application/json",
								Authorization: `Bearer ${opts.apiKey}`,
							},
							redirect: "error",
							signal: AbortSignal.timeout(30000),
							body: JSON.stringify({
								resourceSpans: [
									{
										resource: {
											attributes: [
												{
													key: "service.name",
													value: { stringValue: "helicone-import" },
												},
											],
										},
										scopeSpans: [
											{
												scope: { name: "tracelane.import.helicone" },
												spans: [converted.span],
											},
										],
									},
								],
							}),
						});
					} catch {
						throw new Error(
							`Import stopped at row ${i + 1}: network/timeout/redirect failure; resume with the same cursor`,
						);
					}
					if (response.status !== 200)
						throw new Error(
							`Import stopped at row ${i + 1}: HTTP ${response.status}; cursor retained for retry`,
						);
					let ack: unknown;
					try {
						ack = await response.json();
					} catch {
						throw new Error(
							`Import stopped at row ${i + 1}: invalid ingest acknowledgement; cursor retained for retry`,
						);
					}
					if (!record(ack) || Object.keys(ack).length !== 0)
						throw new Error(
							`Import stopped at row ${i + 1}: unexpected ingest acknowledgement; cursor retained for retry`,
						);
				}
				counts.imported++;
				if (converted.id) seen.add(converted.id);
			}
			if (!opts.dryRun) {
				const temp = `${opts.cursor}.${process.pid}.tmp`;
				let wroteTemp = false;
				try {
					fs.writeFileSync(
						temp,
						JSON.stringify({ version: 1, fingerprint, next: i + 1 }),
						{ mode: 0o600, flag: "wx" },
					);
					wroteTemp = true;
					fs.renameSync(temp, opts.cursor);
				} finally {
					if (wroteTemp && fs.existsSync(temp)) fs.unlinkSync(temp);
				}
			}
		}
		return counts;
	} finally {
		if (lock !== undefined) {
			fs.closeSync(lock);
			fs.unlinkSync(`${opts.cursor}.lock`);
		}
	}
}

// ── Command registration ────────────────────────────────────────────────────

interface Opts {
	traces?: string;
	cursor?: string;
	endpoint?: string;
	env: string;
	output?: string;
	withConfig?: boolean;
	src?: string;
	dryRun?: boolean;
}

export function registerImportHeliconeCommand(program: Command): void {
	program
		.command("import-helicone")
		.description(
			"Import Helicone configuration, or historical request JSON with --traces.",
		)
		.option("--env <path>", "Path to .env file to read", ".env")
		.option(
			"--output <path>",
			"Path to write Tracelane stanza (default: .env.tracelane)",
			".env.tracelane",
		)
		.option(
			"--with-config",
			"Also write a starter tracelane.yaml scaffold (fixed template — edit before use)",
			false,
		)
		.option(
			"--src <dir>",
			"Source dir to review manually for Helicone-Property-* usage — named in the reminder printed with --with-config; nothing is scanned",
			"src/",
		)
		.option("--dry-run", "Print to stdout instead of writing files", false)
		.option(
			"--traces <path>",
			"Import a saved Helicone request JSON array or API response",
		)
		.option(
			"--cursor <path>",
			"Resume state (default: <traces>.tracelane-cursor.json)",
		)
		.option(
			"--endpoint <url>",
			"Destination gateway origin (or TRACELANE_GATEWAY_URL)",
		)
		.action(async (opts: Opts) => {
			if (opts.traces) {
				try {
					const counts = await importHeliconeTraces({
						traces: opts.traces,
						cursor: opts.cursor ?? `${opts.traces}.tracelane-cursor.json`,
						endpoint:
							opts.endpoint ??
							process.env.TRACELANE_GATEWAY_URL ??
							"https://gateway.tracelane.dev",
						apiKey: process.env.TRACELANE_API_KEY ?? "",
						dryRun: opts.dryRun,
					});
					process.stdout.write(
						`${opts.dryRun ? "Dry run: would import" : "Imported (accepted for ingest):"} ${counts.imported}; skipped ${counts.skipped}; reasons: ${JSON.stringify(counts.reasons)}\n`,
					);
				} catch (error) {
					process.stderr.write(
						`Trace import failed: ${error instanceof Error ? error.message : "unknown error"}\n`,
					);
					process.exitCode = 1;
				}
				return;
			}
			const envPath = path.resolve(opts.env);
			const parsed = parseEnvFile(envPath);
			if (parsed.heliconeVars.size === 0) {
				process.stderr.write(
					`tlane import-helicone: no HELICONE_* vars found in ${envPath}.\n  Pass --env <path> if your .env is elsewhere, or remove this step\n  if you only used Helicone via request headers (then see\n  docs/migrations/from-helicone.md header table).\n`,
				);
				process.exit(2);
			}

			const envStanza = emitEnvStanza(parsed);
			const headerTable = emitHeaderTable();

			if (opts.dryRun) {
				process.stdout.write("# === .env.tracelane ===\n");
				process.stdout.write(envStanza);
				process.stdout.write("\n# === Header migration table ===\n");
				process.stdout.write(headerTable);
				return;
			}

			const outPath = path.resolve(opts.output ?? ".env.tracelane");
			fs.writeFileSync(outPath, envStanza, "utf8");
			process.stdout.write(
				`Wrote ${outPath} (${parsed.heliconeVars.size} HELICONE_* vars translated).\n`,
			);
			process.stdout.write("\n");
			process.stdout.write(headerTable);

			if (opts.withConfig) {
				const cfgPath = path.resolve("tracelane.yaml");
				const cfg = [
					"# Tracelane gateway config — minimal scaffold from `tlane import-helicone`.",
					"# Edit to add your full provider list. Reference:",
					"#   https://docs.tracelane.dev/config",
					"",
					"providers:",
					"  - name: anthropic",
					"    api_key_env: ANTHROPIC_API_KEY",
					"  - name: openai",
					"    api_key_env: OPENAI_API_KEY",
					"",
					"observability:",
					"  otlp_endpoint: http://localhost:4317",
					"",
				].join("\n");
				fs.writeFileSync(cfgPath, cfg, "utf8");
				process.stdout.write(
					`Wrote ${cfgPath} (scaffold — extend per docs).\n`,
				);
				if (opts.src) {
					process.stdout.write(
						`Scan ${opts.src} for Helicone-Property-* references (manual step for V1).\n`,
					);
				}
			}
		});
}
