import type { MetadataRoute } from "next";

/**
 * PWA web app manifest. Next serves this at /manifest.webmanifest and links it.
 * The splash/theme colour is a LITERAL by necessity — a JSON manifest cannot read a
 * CSS custom property — and it must be re-synced by hand whenever the canvas token moves.
 *
 * This block said "one of only TWO places in the app that may hold a hardcoded colour",
 * which was an undercount and therefore a false sense of coverage. A tree-wide scan on
 * 2026-08-22 found FOUR, and every one is here for a structural reason, not a carve-out:
 *   · this file                        a JSON manifest cannot read a CSS custom property
 *   · app/global-error.tsx             renders when the stylesheet itself failed to load
 *   · public/audit-user-guide.html     a standalone print/PDF artifact; its own :root
 *   · public/brand/tracelane-mark.svg  GENERATED by scripts/brand/build-brand-assets.py
 * The fourth is the one to watch: its INK is pinned in the generator (`INK = "#0D0D0D"`,
 * the ADR-074 value) and so did NOT move with the P0 swap to `--ink` #171717. Hand-editing
 * the SVG would be overwritten on the next build — change the generator.
 *
 * RE-SYNCED 2026-08-22: #f4f6fa -> #fafaf9, the P0 `--canvas` value. The old value
 * was the "pale blue cast" the P0 brief opens by asking us to remove (B 250 > R 244),
 * and it survived two palette swaps precisely because the hand-sync this comment
 * asks for is the kind of step nobody remembers. It shows up as the splash colour
 * and the browser theme bar on an installed PWA — the first surface a user sees,
 * painted in a colour the app no longer uses anywhere.
 */
export default function manifest(): MetadataRoute.Manifest {
	return {
		name: "Tracelane",
		short_name: "Tracelane",
		description:
			"The flight recorder for AI agents. Full-fidelity traces, a tamper-evident audit ledger you can verify offline, and inline heuristic guardrails.",
		start_url: "/",
		display: "standalone",
		// design-constraint-ok: a web-app manifest is JSON read by the OS installer, not CSS — it cannot reference a custom property, so the value must be a literal. Hand-synced to --canvas (light); it was #f4f6fa and survived two palette swaps because nothing enforced the sync until this marker existed.
		background_color: "#fafaf9", // = --canvas (light)
		// design-constraint-ok: a web-app manifest is JSON read by the OS installer, not CSS — it cannot reference a custom property, so the value must be a literal. Hand-synced to --canvas (light); it was #f4f6fa and survived two palette swaps because nothing enforced the sync until this marker existed.
		theme_color: "#fafaf9", // = --canvas (light)
		// B-252 CLOSED (2026-08-15). These pointed at /brand/logo-icon-light.png and
		// /brand/logo-icon-dark.png at a DECLARED 512x512. Commit 4088da73 deleted both
		// PNGs when the mark moved to inline SVG and left the references behind, so an
		// installed PWA had NO icon at all — in production, from that commit until now.
		//
		// Every size below is the TRUE decoded size, not a claim. A wrong declared size is
		// the same class of defect as a missing file: the manifest asserting something the
		// bytes do not support. Generated + decode-verified by
		// scripts/brand/build-brand-assets.py.
		icons: [
			{
				src: "/brand/pwa-192.png",
				sizes: "192x192",
				type: "image/png",
				purpose: "any",
			},
			{
				src: "/brand/pwa-512.png",
				sizes: "512x512",
				type: "image/png",
				purpose: "any",
			},
		],
	};
}
