// GENERATED by scripts/ci/build-role-capabilities.py — do not edit.
// Source of truth: crates/gateway/src/auth/capability.rs `MATRIX`.
// UI gating only; the gateway is authoritative.

export type CapabilitySlug =
	| "read_traces"
	| "view_spend"
	| "view_settings"
	| "view_keys"
	| "mint_keys"
	| "manage_all_keys"
	| "grant_passthrough"
	| "view_policies"
	| "edit_policies"
	| "edit_budgets"
	| "edit_projects"
	| "manage_alerts"
	| "annotate_traces"
	| "write_prompts"
	| "view_provider_keys"
	| "manage_provider_keys"
	| "manage_billing"
	| "manage_team"
	| "manage_security"
	| "read_control_audit"
	| "manage_controls"
	| "grant_admin_scope";

export type RoleFlags = {
	admin: boolean;
	developer: boolean;
	viewer: boolean;
	billing: boolean;
	unrecognised: boolean;
};

export const ROLE_CAPABILITIES: Record<CapabilitySlug, RoleFlags> = {
	read_traces: {
		admin: true,
		developer: true,
		viewer: true,
		billing: false,
		unrecognised: true,
	},
	view_spend: {
		admin: true,
		developer: true,
		viewer: true,
		billing: true,
		unrecognised: true,
	},
	view_settings: {
		admin: true,
		developer: true,
		viewer: true,
		billing: true,
		unrecognised: false,
	},
	view_keys: {
		admin: true,
		developer: true,
		viewer: true,
		billing: true,
		unrecognised: false,
	},
	mint_keys: {
		admin: true,
		developer: true,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	manage_all_keys: {
		admin: true,
		developer: false,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	grant_passthrough: {
		admin: true,
		developer: false,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	view_policies: {
		admin: true,
		developer: false,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	edit_policies: {
		admin: true,
		developer: false,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	edit_budgets: {
		admin: true,
		developer: false,
		viewer: false,
		billing: true,
		unrecognised: false,
	},
	edit_projects: {
		admin: true,
		developer: false,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	manage_alerts: {
		admin: true,
		developer: true,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	annotate_traces: {
		admin: true,
		developer: true,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	write_prompts: {
		admin: true,
		developer: false,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	view_provider_keys: {
		admin: true,
		developer: false,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	manage_provider_keys: {
		admin: true,
		developer: false,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	manage_billing: {
		admin: true,
		developer: false,
		viewer: false,
		billing: true,
		unrecognised: false,
	},
	manage_team: {
		admin: true,
		developer: false,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	manage_security: {
		admin: true,
		developer: false,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	read_control_audit: {
		admin: true,
		developer: false,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	manage_controls: {
		admin: true,
		developer: false,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
	grant_admin_scope: {
		admin: true,
		developer: false,
		viewer: false,
		billing: false,
		unrecognised: false,
	},
};

export type Role = "admin" | "developer" | "viewer" | "billing";

/** WorkOS slug -> role. `owner`/`admin` -> admin; `member` is the legacy developer. */
export function roleFromSlug(slug: string | null | undefined): Role | null {
	switch (slug) {
		case "owner":
		case "admin":
			return "admin";
		case "developer":
		case "member":
			return "developer";
		case "viewer":
			return "viewer";
		case "billing":
			return "billing";
		default:
			return null;
	}
}

/** Fail-closed: an unrecognised or absent slug gets the `unrecognised` column. */
export function roleCan(
	slug: string | null | undefined,
	capability: CapabilitySlug,
): boolean {
	const flags = ROLE_CAPABILITIES[capability];
	const role = roleFromSlug(slug);
	return role === null ? flags.unrecognised : flags[role];
}
