-- Migration 21: EVL-29 (item 12) — the content snapshot behind a review queue.
--
-- ── DO NOT EDIT THIS FILE AFTER IT HAS BEEN APPLIED ─────────────────────────
-- ClickHouse migrations here are applied PER FILE BY HAND with no journal, so an
-- edited file is a schema that diverges from prod silently. Add a `22_` instead.
--
--
-- ── WHY THIS TABLE EXISTS (founder ruling R228) ─────────────────────────────
--
-- A queue is a SAVED FILTER evaluated at read time (R221.1). Membership is a
-- query, so nothing here stores membership — this table is a CONTENT CACHE keyed
-- on the SPAN, never on a queue. That is the whole reconciliation between R221.1
-- and R228: change a queue's threshold and membership re-evaluates instantly,
-- because no row here encodes which queue anything belonged to.
--
-- THE EXPOSURE IT CLOSES, measured rather than assumed (2026-08-29):
-- `spans` carries `TTL toDate(start_time) + INTERVAL 365 DAY`, and the schema
-- comment for that TTL says in its own words that 365d is "the MAX plan
-- retention (Enterprise) — a fail-safe BACKSTOP, not the per-plan window". The
-- window that actually governs is the entitlement-driven sweep
-- (`crates/gateway/src/retention_sweep.rs`): Free 7 / Builder 30 / Team 90 /
-- Business 180 / Enterprise 365 days. The ONE tenant with content capture on
-- (`a4037bef`) is `free_v1`, so its governing window is SEVEN DAYS — and on prod
-- today **10,225 of its spans are already past that window, 406 of them carrying
-- content**. Nothing has deleted them only because the sweep runs `dryrun`.
--
-- So a queue could list a trace whose content the sweep would already have
-- removed, and the reviewer would meet a dead end at submit. Copying at
-- queue-entry means the bytes a reviewer READS are the bytes the dataset item
-- STORES, and both outlive the source row.
--
--
-- ── THE TTL IS THE POINT, NOT AN AFTERTHOUGHT ───────────────────────────────
--
-- 30 days, as a TABLE-level TTL on a table whose ONLY reason to exist is
-- content. `scripts/ci/check-trace-content-allowlist.py` names exactly this as
-- the precondition before a real customer tenant may be added: *"dedicated
-- columns with a 30-day ClickHouse column TTL"* — impossible on `spans`, whose
-- content lives inside the single `attributes` String column and therefore
-- cannot be expired separately. Here content has its own table, so it can.
--
-- **AND THE QUEUE WINDOW IS PINNED TO THIS NUMBER, NOT TO THE 365-DAY BACKSTOP.**
-- `MAX_QUEUE_WINDOW_HOURS` in `crates/gateway/src/annotation_routes.rs` is
-- 24*30 and a compile-time assertion ties it to this TTL. Before R228 that
-- assertion compared the queue window against the 365-day backstop and passed
-- with a 4x margin that did not exist: against the real 7-day sweep window the
-- queue was 12.8x LONGER than the data it pointed at, inverted from what the
-- assertion claimed. A queue must never be able to reach further back than
-- content survives, and now it cannot.
--
--
-- ── SHAPE ───────────────────────────────────────────────────────────────────
--
-- ReplacingMergeTree(captured_at): the snapshot is written idempotently from two
-- places (the judge at score time, and the queue list on read), so the same span
-- can be offered twice. Replacing on `captured_at` keeps the FIRST-WRITE-WINS
-- semantics we want expressed as last-version-wins over identical bytes: both
-- writers copy the same source row, so the row is stable either way, and a
-- re-copy after the source changed correctly takes the newer capture.
--
-- `PARTITION BY toYYYYMM(captured_at)`: the ONE table in this feature that is
-- time-bounded and append-only, so a partition key is right here for the same
-- reason it was wrong on `dataset_items` (migration 18 §PARTITIONING) — TTL can
-- drop whole partitions instead of mutating, and every read filters a time range.
CREATE TABLE IF NOT EXISTS trace_content_snapshots (
    tenant_id    String,                  -- validated claim ONLY, never a body
    trace_id     String,
    -- The span the content came FROM. A trace-level review carries the OBS-18
    -- `''` sentinel in `trace_annotations`, but content always comes from a
    -- concrete span — conflating those two is what made every `trace_error`
    -- review 404 before this migration.
    span_id      String,
    input        String,                  -- JSON: Vec<shared::model::Message>
    system       String DEFAULT '',
    input_hash   FixedString(64),         -- sha256 hex, the dataset dedupe key
    -- MILLIS. `datetime64_millis_now()` — never `timestamp_micros()`, which is
    -- accepted silently and reads back as the year 2299 (migration 18's trap).
    captured_at  DateTime64(3, 'UTC')
)
ENGINE = ReplacingMergeTree(captured_at)
ORDER BY (tenant_id, trace_id, span_id)
PARTITION BY toYYYYMM(captured_at)
TTL toDate(captured_at) + INTERVAL 30 DAY;
