-- Migration 22: B-379 — the two most-run queries read the WINDOW, not the tenant's history.
--
-- ── DO NOT EDIT THIS FILE AFTER IT HAS BEEN APPLIED ─────────────────────────
-- ClickHouse migrations here are applied PER FILE BY HAND with no journal, so an
-- edited file is a schema that diverges from prod silently. Add a `23_` instead.
--
-- ── WHAT THE REVIEW MEASURED (2026-09-12, prod's pinned 24.12.6.70, this repo's DDL) ──
--
--   "last 50 traces"  (trace_summaries)   1,007,616 rows / 123.91 MiB read to return 50
--   1-hour breakdown  (spans)             51x the rows a time-first key reads
--   attributes ngram search               1,007,616 rows — the index pruned NOTHING
--
-- MEASURED on the throwaway (this DDL, 1M spans in one tenant), the numbers behind the
-- decision, read from system.query_log (read_rows / read_bytes):
--   1-hour breakdown on spans      384,602 / 13.5 MB  →   20,247 / 0.7 MB   (19x)
--   last-50 list, trace_summaries  1,000,576 / 72 MB  →  238,720 / 32 MB at a 7-day window,
--                                                        33,920 / 4.5 MB at 1 day (projection)
--   single-trace waterfall          24,576 / 1.1 MB   →    8,192 / 0.5 MB   (bloom)
--   substring search, no window   1,041,536 / 139 MB  →  windowed: see the index note below
--
-- `spans` is `ORDER BY (tenant_id, trace_id, span_id)`: `trace_id` is random, so a
-- predicate on `start_time` — which 10 of the 22 `FROM spans` sites in trace_reads.rs
-- carry — prunes no granule at all. `trace_summaries` is `PARTITION BY tuple()` +
-- `ORDER BY (tenant_id, trace_id)` BY DESIGN (migration 15 / B-243: partial rows from two
-- ingest flushes must land on the same key to MERGE), and `FINAL` — which every reader
-- uses — disables projections. Both queries are O(tenant history), and the list query
-- hits `max_rows_to_read` at ~50M traces and FAILS, not slows.
--
-- Prod on the day (read from the node): spans 15,053 rows / 2.06 MiB; trace_summaries
-- 14,944 rows. The rewrite is seconds now and days at 50M rows.
--
-- ── PART 1: `spans` — time-first sort key, trace_id bloom filter ───────────────────
--
-- The columns, MATERIALIZED expressions, indexes and TTL are prod's own `SHOW CREATE
-- TABLE` (2026-09-12) — NOT schema.sql's, which B-369 showed can differ from prod. Only
-- the ORDER BY line and one new index change.
--
-- `(tenant_id, toStartOfHour(start_time), trace_id, span_id)` is still a valid
-- ReplacingMergeTree dedup key: a span's `start_time` is the span's own, deterministic
-- per span, so a redelivered duplicate lands on the same key. HOUR, not day: the second
-- key column decides how many granules an N-hour window touches, and hour is the finest
-- bucket that keeps a trace's spans adjacent.
--
-- The single-trace waterfall (`WHERE trace_id = ?`, no time predicate) loses its key
-- prefix and gets a bloom filter instead — a trace's spans sit in one or two hourly
-- buckets, so the bloom prunes to those granules.

CREATE TABLE IF NOT EXISTS tracelane.spans_v2
(
    `tenant_id` String,
    `trace_id` String,
    `span_id` String,
    `parent_span_id` Nullable(String),
    `name` String,
    `start_time` DateTime64(6, 'UTC'),
    `end_time` DateTime64(6, 'UTC'),
    `duration_us` Int64 MATERIALIZED dateDiff('microsecond', start_time, end_time),
    `status_code` UInt8,
    `status_message` String DEFAULT '',
    `attributes` String DEFAULT '{}',
    `aft_ids` Array(String) DEFAULT [],
    `intervention` UInt8 DEFAULT 0,
    `ingested_at` DateTime64(3, 'UTC') DEFAULT now64(),
    `gateway_overhead_us` UInt32 MATERIALIZED JSONExtractUInt(attributes, 'tracelane_gateway_overhead_us'),
    `api_key_id` String MATERIALIZED JSONExtractString(attributes, 'tracelane_api_key_id'),
    `cost_usd` Float64 MATERIALIZED JSONExtractFloat(attributes, 'gen_ai_usage_cost'),
    `cost_usd_present` UInt8 MATERIALIZED toUInt8(JSONHas(attributes, 'gen_ai_usage_cost')),
    INDEX idx_name_ngram name TYPE ngrambf_v1(4, 4096, 3, 0) GRANULARITY 4,
    -- `idx_attributes_ngram` (ngrambf_v1(4, 8192, 3, 0) GRANULARITY 4 over the JSON
    -- blob) is DELETED here, on measurement (B-379 spec §2d, 24.12 throwaway, 1M spans
    -- in one tenant, a 1-in-1M needle): it pruned NOTHING (1,003,903 rows read of
    -- 1,000,000); an 8x larger bloom at GRANULARITY 1 pruned 27% for 10.8 MB of index;
    -- the time-first key below bounds the same search to the WINDOW instead — 7 days:
    -- 249,623 rows / 35 MB; 1 day: 53,015 rows / 7.5 MB; unwindowed: 1,041,536 rows /
    -- 139 MB. A substring search over a ~450-byte JSON value is a scan by nature; the
    -- read path now always windows it. `idx_name_ngram` stays — `name` is a short
    -- column and the same index shape prunes well there.
    INDEX idx_api_key_id api_key_id TYPE bloom_filter(0.01) GRANULARITY 4,
    INDEX idx_trace_id trace_id TYPE bloom_filter(0.01) GRANULARITY 1
)
ENGINE = ReplacingMergeTree(ingested_at)
PARTITION BY toYYYYMM(start_time)
ORDER BY (tenant_id, toStartOfHour(start_time), trace_id, span_id)
TTL toDate(start_time) + toIntervalDay(365)
SETTINGS index_granularity = 8192;

-- 1b. Timestamps for the two windows below. ClickHouse has no session variables, so a
--     tiny marks table carries them; it is dropped at the end.
CREATE TABLE IF NOT EXISTS tracelane.migration_22_marks (k String, t DateTime64(3, 'UTC'))
ENGINE = MergeTree ORDER BY k;
INSERT INTO tracelane.migration_22_marks VALUES ('snapshot', now64(3));

-- 2. Copy. MATERIALIZED columns are recomputed on insert, so the explicit column list
--    names only the stored ones. `ingested_at` is COPIED, not defaulted, so the
--    Replacing version column keeps its meaning across the swap.
INSERT INTO tracelane.spans_v2
    (tenant_id, trace_id, span_id, parent_span_id, name, start_time, end_time,
     status_code, status_message, attributes, aft_ids, intervention, ingested_at)
SELECT tenant_id, trace_id, span_id, parent_span_id, name, start_time, end_time,
       status_code, status_message, attributes, aft_ids, intervention, ingested_at
FROM tracelane.spans;

-- 3. Detach the MV FIRST so no insert during the swap fans out to a table that is
--    mid-rename. Ingest keeps inserting into `tracelane.spans` BY NAME throughout —
--    after the EXCHANGE that name is the new table, which is the point. From this
--    instant until step 6 creates the new MV, inserted spans are NOT summarised; the
--    mark bounds step 7 EXACTLY (a row with ingested_at before it was summarised by
--    the MV that existed; re-summarising it would double-count span_count).
INSERT INTO tracelane.migration_22_marks VALUES ('mv_dropped', now64(3));
DROP TABLE IF EXISTS tracelane.mv_trace_summaries;

-- 4. Atomic swap. The old table becomes `spans_v2` (the rollback: EXCHANGE again).
EXCHANGE TABLES tracelane.spans AND tracelane.spans_v2;

-- 5. Rows that landed in the OLD table between step 2's snapshot and step 4's swap.
--    Replacing dedup on the key makes any overlap at the boundary harmless; the mark
--    keeps this a delta rather than a second full copy.
INSERT INTO tracelane.spans
    (tenant_id, trace_id, span_id, parent_span_id, name, start_time, end_time,
     status_code, status_message, attributes, aft_ids, intervention, ingested_at)
SELECT tenant_id, trace_id, span_id, parent_span_id, name, start_time, end_time,
       status_code, status_message, attributes, aft_ids, intervention, ingested_at
FROM tracelane.spans_v2
WHERE ingested_at >= (SELECT t FROM tracelane.migration_22_marks WHERE k = 'snapshot');

-- 6. The MV, recreated against the NEW `tracelane.spans`. Byte-for-byte the SELECT prod
--    runs today (SHOW CREATE TABLE mv_trace_summaries, 2026-09-12). An MV binds to its
--    source table OBJECT, so the one that existed still pointed at the old table after
--    the exchange — recreating it is not optional.
CREATE MATERIALIZED VIEW IF NOT EXISTS tracelane.mv_trace_summaries
TO tracelane.trace_summaries
AS
SELECT
    s.tenant_id AS tenant_id,
    s.trace_id AS trace_id,
    maxIf(s.name, s.parent_span_id IS NULL) AS root_name,
    min(s.start_time) AS start_time,
    max(s.end_time) AS end_time,
    toUInt64(count()) AS span_count,
    toUInt64(countIf(s.status_code = 2)) AS error_count,
    max(s.intervention) AS intervention,
    max(coalesce(nullIf(JSONExtractString(s.attributes, 'gen_ai_response_model'), ''), nullIf(JSONExtractString(s.attributes, 'gen_ai_request_model'), ''), nullIf(JSONExtractString(s.attributes, 'gen_ai.response.model'), ''), nullIf(JSONExtractString(s.attributes, 'gen_ai.request.model'), ''), JSONExtractString(s.attributes, 'llm.model_name'))) AS model
FROM tracelane.spans AS s
GROUP BY
    s.tenant_id,
    s.trace_id;
INSERT INTO tracelane.migration_22_marks VALUES ('mv_created', now64(3));

-- 7. Rows inserted between the marks were not summarised (no MV existed). Re-derive the
--    summaries for EXACTLY that window through the SAME select; AggregatingMergeTree
--    merges them into any partial rows already there. The bounds are the marks, not a
--    margin: a span summarised twice is a trace whose span_count reads double.
INSERT INTO tracelane.trace_summaries
SELECT
    s.tenant_id AS tenant_id,
    s.trace_id AS trace_id,
    maxIf(s.name, s.parent_span_id IS NULL) AS root_name,
    min(s.start_time) AS start_time,
    max(s.end_time) AS end_time,
    toUInt64(count()) AS span_count,
    toUInt64(countIf(s.status_code = 2)) AS error_count,
    max(s.intervention) AS intervention,
    max(coalesce(nullIf(JSONExtractString(s.attributes, 'gen_ai_response_model'), ''), nullIf(JSONExtractString(s.attributes, 'gen_ai_request_model'), ''), nullIf(JSONExtractString(s.attributes, 'gen_ai.response.model'), ''), nullIf(JSONExtractString(s.attributes, 'gen_ai.request.model'), ''), JSONExtractString(s.attributes, 'llm.model_name'))) AS model
FROM tracelane.spans AS s
WHERE s.ingested_at >= (SELECT t FROM tracelane.migration_22_marks WHERE k = 'mv_dropped')
  AND s.ingested_at <  (SELECT t FROM tracelane.migration_22_marks WHERE k = 'mv_created')
GROUP BY s.tenant_id, s.trace_id;

DROP TABLE IF EXISTS tracelane.migration_22_marks;

-- ── PART 2: `trace_summaries` — a time-ordered PROJECTION; the table's key STAYS ──────
--
-- `PARTITION BY tuple()` and `ORDER BY (tenant_id, trace_id)` are B-243's constraint and
-- hold. What changes is how the list is READ: the read path (trace_reads.rs, same
-- change) stops using `FINAL` — which forbids projections — and does the merge itself
-- with GROUP BY (SimpleAggregateFunction(max/min/sum) merges ARE max/min/sum), over
-- only the rows this projection returns for the window. ClickHouse cannot use a
-- projection under FINAL; it can under GROUP BY.

-- 24.12 refuses a projection on an AggregatingMergeTree unless told what to do with
-- it on a deduplicating merge: `rebuild` recomputes the projection part from the merged
-- rows, which is the only mode that keeps it correct as partial rows combine.
ALTER TABLE tracelane.trace_summaries
    MODIFY SETTING deduplicate_merge_projection_mode = 'rebuild';

-- And on a lightweight DELETE (the retention sweep, `retention_sweep.rs`): 24.12 refuses
-- one on a table with projections (Code 344) unless the TABLE setting says otherwise —
-- the query-level setting of the same name does NOT override it (measured). `rebuild`
-- keeps the list query's projection on the parts the delete touches.
ALTER TABLE tracelane.trace_summaries
    MODIFY SETTING lightweight_mutation_projection_mode = 'rebuild';

ALTER TABLE tracelane.trace_summaries
    ADD PROJECTION IF NOT EXISTS p_by_time (SELECT * ORDER BY tenant_id, start_time);

ALTER TABLE tracelane.trace_summaries MATERIALIZE PROJECTION p_by_time;

-- ── VERIFY (run by hand; the numbers are the proof) ───────────────────────────────
--   SELECT count() FROM tracelane.spans;                      -- == the pre-migration count (+ new rows)
--   SELECT count() FROM tracelane.spans_v2;                   -- the old table, rollback
--   SHOW CREATE TABLE tracelane.spans;                        -- ORDER BY (tenant_id, toStartOfHour(start_time), trace_id, span_id)
--   SELECT name FROM system.projection_parts WHERE table='trace_summaries' AND active LIMIT 1;  -- p_by_time
--   EXPLAIN indexes = 1 SELECT count() FROM tracelane.spans WHERE tenant_id = '<t>' AND start_time >= now() - INTERVAL 1 HOUR;
--     -- PrimaryKey: Parts/Granules pruned to the hour, not the tenant
-- Then, once the list and breakdown routes have been read against it for a day:
--   DROP TABLE tracelane.spans_v2;
