-- Migration 23: B-379 / B-387 — `trace_summaries`' projection is rebuilt clean and a
-- lightweight DELETE on the table is REFUSED again.
--
-- ── DO NOT EDIT THIS FILE AFTER IT HAS BEEN APPLIED (applied on prod 2026-09-12 19:20 UTC) ──
--
-- WHAT HAPPENED. Migration 22 set `lightweight_mutation_projection_mode = 'rebuild'` so the
-- retention sweep's lightweight DELETE would be accepted on the projected table. The
-- first enforce sweep on prod (18:54 UTC) deleted 14,133 summary rows for one tenant; the
-- next sweep (19:07) found the SAME 14,133 rows again. Measured on the node:
--   count() via the projection ........ 14,133      (deleted rows, still served)
--   count() with optimize_use_projections = 0 ...... 0
--   count() FINAL ...................... 0
-- and after an OPTIMIZE FINAL merge the projection part held 14,980 rows over a
-- 794-row base. ClickHouse 24.12 rebuilds the projection from the UN-MASKED rows on a
-- lightweight delete, so any read the planner routes through `p_by_time` returns rows
-- the sweep removed — the privacy promise failing at read time.
--
-- WHAT THIS DOES. (1) Drops and re-materialises the projection from the merged base, so
-- projection rows == base rows. (2) Puts the setting back at its default, `throw`: a
-- lightweight DELETE on this table is refused with Code 344 instead of trusted. The sweep
-- now uses a HEAVY `ALTER TABLE … DELETE` for this table (measured on a 24.12 throwaway:
-- projection 500 / base 500 before and after a merge).
--
-- Applied by hand on prod BEFORE this file existed (the repair was the incident response);
-- this file is the record and the self-host path. Idempotent.

ALTER TABLE tracelane.trace_summaries DROP PROJECTION IF EXISTS p_by_time;
ALTER TABLE tracelane.trace_summaries MODIFY SETTING lightweight_mutation_projection_mode = 'throw';
ALTER TABLE tracelane.trace_summaries ADD PROJECTION IF NOT EXISTS p_by_time (SELECT * ORDER BY tenant_id, start_time);
ALTER TABLE tracelane.trace_summaries MATERIALIZE PROJECTION p_by_time SETTINGS mutations_sync = 2;

-- ── VERIFY ────────────────────────────────────────────────────────────────────────
--   SELECT name, rows FROM system.parts WHERE table='trace_summaries' AND active;
--   SELECT name, rows FROM system.projection_parts WHERE table='trace_summaries' AND active;
--     -- the two row counts agree
--   DELETE FROM tracelane.trace_summaries WHERE tenant_id = 'none';   -- Code 344, refused
