#!/usr/bin/env python3
"""Generate the gateway's provider catalog and model price table.

GWY-42. Adding a provider used to cost ~15 lines of Rust across six files plus
~10 count/claim edits across six more — a struct field, five `match` arms, a
BYOK allowlist, a TS dropdown const, three CI-enforced doc comments. This script
makes it a row in a data file.

FOUR OUTPUTS, all checked in, all re-derived by `--check`:

  crates/gateway/providers.tsv     one row per OpenAI-compatible provider
  crates/gateway/model_prices.tsv  one row per priced model
  apps/web/.../provider-catalog.generated.ts   the dashboard BYOK dropdown
  the provider tables inside docs/guides/providers.md + apps/docs/providers.mdx

The two doc pages used to enumerate the catalog BY HAND under headings that
carried their own counts — "Dedicated adapters (7)", "OpenAI-compatible
adapters (28)". Both were wrong: the dedicated table said seven and listed six,
omitted Vertex, and counted `openai`, which is a catalog row and not a native
adapter at all. Worse, `check-provider-count.py` could not see either heading —
a count inside parentheses matches none of its claim shapes — so the guard
exited 0 while both published pages lied by 134 entries. The enumeration is
generated between markers now, and the prose around it names no bare count.

TWO INPUTS, and the split matters:

  1. THE PROVIDERS THAT ALREADY ROUTE come from `providers.tsv` ITSELF (see
     `parse_existing`). Their base URLs, env vars and model prefixes are running
     in production and are known-good; taking them from an external catalog
     would silently re-point live traffic. This script therefore treats the
     checked-in rows as authoritative and refuses to overwrite a single field.
     That is what makes a refresh behaviour-preserving rather than merely
     plausible. The FIRST generation bootstrapped these rows out of the
     hand-written `match` arms in `providers/mod.rs`; that code is gone.

  2. NEW PROVIDERS come from models.dev's `api.json` (MIT, Copyright (c) 2025
     models.dev — see crates/gateway/NOTICE-models.dev). It is the neutral
     third-party catalog: 191 providers (provider-count-exempt: that is
     models.dev's own count, not ours), each with a base URL, a key env var, an
     OpenAI-compat marker and per-model pricing. LiteLLM's equivalent file is
     also MIT and was considered; models.dev was chosen because it is not a
     direct competitor's artifact. OpenRouter's /api/v1/models was rejected
     outright — its Terms prohibit automated copying.

A new provider gets ONLY a namespaced `<id>/` prefix, never a bare model-name
prefix. A bare prefix is how `llama-3.3-70b` silently dispatched to Groq with
Groq's key while its BYOK row said "anthropic" (the B-126 class), and 139 new
rows is 139 chances to do it again. The six bare-prefix providers we already
have keep theirs, because they are already live.

Usage:
    build-provider-catalog.py            regenerate from a fresh fetch
    build-provider-catalog.py --check    fail if the checked-in files are stale
    build-provider-catalog.py --selftest prove the guards refuse bad input
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "crates/gateway/providers.tsv"
PRICES = ROOT / "crates/gateway/model_prices.tsv"
DROPDOWN = ROOT / "apps/web/components/settings/provider-catalog.generated.ts"
# The two published provider pages. Their enumeration is spliced between the
# markers below; every other line on either page stays hand-written.
DOC_PAGES = (ROOT / "docs/guides/providers.md", ROOT / "apps/docs/providers.mdx")
# Read for the native-adapter half of the doc table. Never written.
MOD_RS = ROOT / "crates/gateway/src/providers/mod.rs"
SOURCE_URL = "https://models.dev/api.json"

# Deliberately free of "GENERATED BY" / "DO NOT EDIT": `check-provider-count.py`
# sniffs the first 4 KB of every file for those phrases and skips the whole file
# as machine-written. These pages must stay SCANNED — the hedged provider claim
# in their hand-written prose is exactly what that guard is for.
DOC_BEGIN = "BEGIN GENERATED PROVIDER TABLE"
DOC_END = "END GENERATED PROVIDER TABLE"

# Providers with a dedicated Rust adapter. They are NOT catalog rows — their wire
# format is genuinely different — but they ARE providers, so the count includes
# them and `is_known_provider` must still accept them.
NATIVE = ["anthropic", "google", "vertex", "bedrock", "azure", "cohere"]
# `openai` is a CATALOG row (it was always an OpenAiProvider), not a native
# adapter — it appears in the dropdown via the catalog, with a nicer label.

# models.dev ids that name a provider we already carry under a different id.
# Getting this wrong ships the same provider twice under two names, which is
# exactly the kind of inflated count this repo has been burned by.
ALIASES = {
    "togetherai": "together",
    "fireworks-ai": "fireworks",
    "cloudflare-workers-ai": "cloudflare",
    "google-vertex": "vertex",
    "google-vertex-anthropic": "vertex",
    "amazon-bedrock": "bedrock",
    "azure-openai": "azure",
    "01-ai": "yi",
    "alephalpha": "aleph-alpha",
    "aleph-alpha": "aleph-alpha",
    "moonshotai": "moonshot",
    "novita-ai": "novita",
    "nvidia-nim": "nvidia",
    "lambda-labs": "lambda",
    "sambanova-cloud": "sambanova",
    "hyperbolic-ai": "hyperbolic",
}

# The TSV header row. Written literally rather than joined, so the file's column
# order is visible in one glance — `catalog.rs` reads these positionally.
HEADER = "id\tlabel\tbase_url\tbase_url_env\tapi_key_env\tprefixes"

# Display names for the ids the catalog does not carry a label for. `openai` is
# here because it IS a catalog row whose upstream label reads worse than this
# one; the six entries after it are the native adapters, which have no row.
# One map, so the dashboard dropdown and the published tables cannot disagree.
NATIVE_LABELS = {
    "anthropic": "Anthropic",
    "openai": "OpenAI",
    "google": "Google (Gemini)",
    "vertex": "Google Vertex AI",
    "bedrock": "AWS Bedrock",
    "azure": "Azure OpenAI",
    "cohere": "Cohere",
}


def canon(pid: str) -> str:
    return ALIASES.get(pid, pid)


# ── input 1: the checked-in catalog, authoritative for what already routes ───


def parse_existing() -> dict[str, list[str]]:
    """Read the rows already in `providers.tsv`. They are NEVER overwritten.

    This is the safety property of the whole generator. Every row here is a
    provider that routes in production; its base URL, key env var and model
    prefixes are known-good. Letting an upstream catalog refresh re-point one
    would move live traffic — and, because the BYOK key is fetched by provider
    id, would send a tenant's credential to a host they never chose. So a
    regeneration can only ADD rows and refresh PRICES; it cannot edit a
    provider that already exists.

    The very first generation bootstrapped these rows out of the hand-written
    `match` arms in `providers/mod.rs`. That code is gone — the catalog replaced
    it — so the file itself is now the source, and `git log providers.tsv` is
    the history.
    """
    if not CATALOG.exists():
        sys.exit(
            f"FAIL — {CATALOG.relative_to(ROOT)} is missing. It is the authoritative "
            "record of every provider that already routes and cannot be reconstructed "
            "from models.dev (whose base URLs differ from the ones in production). "
            "Restore it from git rather than regenerating from scratch."
        )
    rows: dict[str, list[str]] = {}
    for line in CATALOG.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith(("#", "id\t")):
            continue
        f = line.split("\t")
        if len(f) != 6:
            sys.exit(f"FAIL — malformed row in {CATALOG.name}: {line!r}")
        rows[f[0]] = f
    if len(rows) < 29:
        sys.exit(
            f"FAIL — parsed only {len(rows)} rows from {CATALOG.name}; expected >= 29 "
            "(the set that already routed before GWY-42). Refusing to emit a catalog "
            "that would silently drop live providers."
        )
    return rows


# ── input 2: models.dev, for NEW providers and for all pricing ────────────────


def fetch(url: str) -> tuple[dict, str]:
    # models.dev answers 403 to urllib's default User-Agent. A named agent is
    # also the courteous thing when pulling someone else's catalog on a schedule.
    req = urllib.request.Request(
        url, headers={"User-Agent": "tracelane-provider-catalog/1.0"}
    )
    with urllib.request.urlopen(req, timeout=120) as r:
        raw = r.read()
    return json.loads(raw), hashlib.sha256(raw).hexdigest()


def normalise_base(api: str) -> str | None:
    """Strip the `/v1` the adapter appends itself, and reject what we can't use.

    `OpenAiProvider::chat` builds `{base_url}/v1/chat/completions`, so a base URL
    that already ends in `/v1` would produce `/v1/v1/chat/completions` — a 404
    that looks exactly like a provider outage.
    """
    api = api.rstrip("/")
    if "${" in api:  # needs per-deployment templating (e.g. an account id)
        return None
    api = api.removesuffix("/v1")
    if not api.startswith("https://"):
        return None  # http:// is an SSRF-guard refusal in release builds anyway
    return api


def build_rows(existing: dict[str, list[str]], md: dict) -> list[list[str]]:
    rows: list[list[str]] = [existing[k] for k in sorted(existing)]
    have = set(existing)

    for raw_id, v in sorted(md.items()):
        pid = canon(raw_id)
        if pid in have:
            continue
        if v.get("npm") != "@ai-sdk/openai-compatible":
            continue  # a bespoke wire format needs a real adapter, not a row
        base = normalise_base(v.get("api") or "")
        if not base or not v.get("env"):
            continue
        have.add(pid)
        rows.append(
            [
                pid,
                v.get("name") or pid,
                base,
                re.sub(r"[^A-Z0-9]", "_", pid.upper()) + "_BASE_URL",
                v["env"][0],
                f"{pid}/",  # namespaced ONLY — see the module docstring
            ]
        )
    return rows


# ── the guards. Each refuses a specific way this file can be wrong ────────────


def check_rows(rows: list[list[str]]) -> list[str]:
    errs: list[str] = []
    seen_id: set[str] = set()
    bare: dict[str, str] = {}
    namespaced: dict[str, str] = {}

    for pid, label, base, base_env, key_env, prefixes in rows:
        if pid in seen_id:
            errs.append(f"duplicate provider id `{pid}`")
        seen_id.add(pid)
        if not re.fullmatch(r"[a-z0-9][a-z0-9._-]*", pid):
            errs.append(f"provider id `{pid}` is not [a-z0-9._-]")
        if any("\t" in f for f in (pid, label, base, base_env, key_env, prefixes)):
            errs.append(f"`{pid}` contains a TAB, which would shift every column")
        if not base.startswith("https://") and not base.startswith("http://localhost"):
            errs.append(f"`{pid}` base_url `{base}` is neither https nor localhost")
        if base.rstrip("/").endswith("/v1"):
            errs.append(
                f"`{pid}` base_url ends in /v1; the adapter appends it (double-/v1 404)"
            )
        for p in prefixes.split(","):
            if not p:
                errs.append(f"`{pid}` has an empty prefix")
                continue
            if "/" in p or p.startswith("@"):
                if p in namespaced:
                    errs.append(
                        f"prefix `{p}` claimed by both `{namespaced[p]}` and `{pid}`"
                    )
                namespaced[p] = pid
            else:
                if p in bare:
                    errs.append(
                        f"bare prefix `{p}` claimed by both `{bare[p]}` and `{pid}`"
                    )
                bare[p] = pid

    # A bare prefix that is a strict prefix of another bare prefix is legal ONLY
    # because the resolver is longest-match-wins. State it here so the property
    # the resolver depends on is asserted by a guard and not merely believed.
    for a in bare:
        for b in bare:
            if a != b and b.startswith(a) and len(b) > len(a):
                pass  # longest-match resolves it; recorded, not an error
    return errs


def render(rows: list[list[str]], src_sha: str) -> str:
    lines = [
        "# GENERATED by scripts/ci/build-provider-catalog.py — DO NOT EDIT BY HAND.",
        "# One OpenAI-compatible provider per row. Native adapters (anthropic, google,",
        "# vertex, bedrock, azure, cohere) are NOT here: their wire format differs and",
        "# they stay as typed Rust adapters.",
        "#",
        "# `prefixes` is comma-separated. A prefix containing `/` (or starting `@`) is",
        "# NAMESPACED and is matched first; a bare prefix is matched afterwards,",
        "# LONGEST FIRST — which is what keeps `llama-3.1-sonar` on perplexity while",
        "# `llama-3.3-70b` goes to groq, exactly as the hand-written match arms did.",
        "#",
        f"# New rows derive from {SOURCE_URL} (MIT, (c) 2025 models.dev).",
        f"# source sha256: {src_sha}",
        "# Existing rows derive from crates/gateway/src/providers/mod.rs itself, so a",
        "# regeneration can never re-point live production traffic.",
        HEADER,
    ]
    lines += ["\t".join(r) for r in rows]
    return "\n".join(lines) + "\n"


def render_prices(md: dict, src_sha: str) -> str:
    """Emit one row per (provider, model), NOT per model.

    The same model id is sold at different prices by different hosts —
    `gpt-4o` on Azure is not `gpt-4o` on OpenAI, and `llama-3.3-70b` costs
    something different on Groq than on Together. Keying the table by model
    alone would price a request at whichever host happened to sort first, which
    is a wrong number rendered with the confidence of a right one. That is the
    B-068 shape applied to money.

    A bare-model fallback row is emitted separately (provider `*`) for callers
    whose model string carries no provider hint, so an unprefixed `gpt-4o` still
    prices — but from the provider that actually owns the name where we can tell.
    """
    lines = [
        "# GENERATED by scripts/ci/build-provider-catalog.py — DO NOT EDIT BY HAND.",
        "# USD per MILLION tokens, as models.dev publishes them.",
        "#",
        "# The gateway's own hand-verified cards in pricing.rs are consulted FIRST and",
        "# WIN. This table only extends coverage; it never re-prices a model the founder",
        "# has verified. Lookup order in `pricing::cost_usd` is: verified card ->",
        "# (provider, model) -> (provider, model minus its `provider/` prefix) ->",
        "# (*, model). A miss is still None, never zero.",
        "#",
        f"# source: {SOURCE_URL} (MIT, (c) 2025 models.dev)  sha256: {src_sha}",
        "provider\tmodel\tinput\toutput\tcache_read",
    ]

    rows: list[str] = []
    seen: set[tuple[str, str]] = set()
    # `*` fallback: only claimed when exactly ONE provider sells that model id.
    # An ambiguous bare name gets NO fallback row rather than a coin toss.
    owners: dict[str, set[str]] = {}
    priced: dict[tuple[str, str], tuple] = {}

    for raw_id, v in sorted(md.items()):
        pid = canon(raw_id)
        for mid, m in sorted(v.get("models", {}).items()):
            cost = m.get("cost") or {}
            if "input" not in cost or "output" not in cost:
                continue
            if "\t" in mid or "\t" in pid:
                continue
            # FLOATING ALIASES ARE NEVER PRICED. `gemini-flash-latest` and
            # `mistral-large-latest` point at a different model over time, so a
            # rate recorded against them is a rate for a model we cannot name.
            # pricing.rs has asserted this since before the catalog existed
            # (`floating_latest_aliases_are_unpriced`) and the catalog must not
            # quietly overturn a standing honesty policy by widening coverage.
            if mid.endswith(("-latest", ":latest")) or mid == "latest":
                continue
            key = (pid, mid)
            if key in seen:
                continue
            seen.add(key)
            rec = (cost["input"], cost["output"], cost.get("cache_read", ""))
            priced[key] = rec
            owners.setdefault(mid, set()).add(pid)

    for (pid, mid), (i, o, c) in sorted(priced.items()):
        rows.append(f"{pid}\t{mid}\t{i}\t{o}\t{c}")
    for mid, who in sorted(owners.items()):
        if len(who) == 1:
            pid = next(iter(who))
            i, o, c = priced[(pid, mid)]
            rows.append(f"*\t{mid}\t{i}\t{o}\t{c}")

    return "\n".join(lines + rows) + "\n"


def render_dropdown(rows: list[list[str]]) -> str:
    """The dashboard's BYOK provider list, generated from the same catalog.

    This was a hand-maintained TS const, and B-145 is what that cost: Groq,
    Together, Fireworks and OpenRouter routed fine and were storable by the API,
    but were missing from the dropdown, so a customer had no way to add a key
    from the UI. "Routed ≠ usable ≠ OFFERED" is three lists, and the third one
    is the one a customer actually touches.

    Generated rather than served from an endpoint on purpose: this is static
    data that changes only when we ship, so a runtime fetch would add a loading
    state, an error state and a network failure mode to a <select> — cost with
    no benefit. `check-byok-provider-coverage.py` proves it matches the gateway.
    """
    hints = {
        "anthropic": "starts with sk-ant-",
        "openai": "starts with sk-",
    }
    lines = [
        "// GENERATED by scripts/ci/build-provider-catalog.py — DO NOT EDIT BY HAND.",
        "// Source: crates/gateway/providers.tsv + the six native adapters.",
        "//",
        "// Every provider the gateway can route to AND store a BYOK key for. The",
        "// gateway re-validates on upload and rejects an unknown id with 400, so this",
        "// list is a convenience, never the security boundary.",
        "",
        "export interface CatalogProvider {",
        "\tid: string;",
        "\tlabel: string;",
        "\thint?: string;",
        "}",
        "",
        "export const PROVIDERS: ReadonlyArray<CatalogProvider> = [",
    ]
    native_labels = NATIVE_LABELS
    seen: set[str] = set()
    out: list[tuple[str, str]] = []
    for pid in NATIVE:
        out.append((pid, native_labels.get(pid, pid.title())))
        seen.add(pid)
    for pid, label, *_ in rows:
        if pid in seen:
            continue
        seen.add(pid)
        out.append((pid, native_labels.get(pid, label)))

    for pid, label in sorted(out, key=lambda r: r[1].lower()):
        h = hints.get(pid)
        esc = label.replace("\\", "\\\\").replace('"', '\\"')
        if h:
            lines.append(f'\t{{ id: "{pid}", label: "{esc}", hint: "{h}" }},')
        else:
            lines.append(f'\t{{ id: "{pid}", label: "{esc}" }},')
    lines += [
        "];",
        "",
        "export const PROVIDER_LABEL: ReadonlyMap<string, string> = new Map(",
        "\tPROVIDERS.map((p) => [p.id, p.label]),",
        ");",
        "",
    ]
    return "\n".join(lines)


# ── output 4: the enumeration inside the two published provider pages ────────


class SpliceError(Exception):
    """A doc page cannot take the generated block. Never a silent no-op."""


def parse_native_adapters(mod_src: str) -> list[tuple[str, list[str], str]]:
    """`(id, model prefixes, credential env var)` per native adapter, from mod.rs.

    Derived from the source rather than restated here, because the restated
    version is the one that rotted: the published page announced seven dedicated
    adapters, listed six, omitted Vertex entirely, and counted `openai` — which
    `providers/mod.rs` says in as many words is a catalog row.

    Three parses, each fail-loud. A parser that quietly returns fewer adapters
    than exist would publish a shorter table and look fine doing it.
    """
    fields = re.search(r"pub struct ProviderRegistry\s*\{(.*?)\n\}", mod_src, re.DOTALL)
    if not fields:
        raise SpliceError(
            "could not locate `pub struct ProviderRegistry` in "
            f"{MOD_RS.relative_to(ROOT)} — the source shape changed. Fix this parser "
            "rather than publishing whatever it managed to find."
        )
    # A field typed `<Name>Provider`, which is what an adapter is. Counting `pub`
    # fields instead would sweep in the private `compat` map — the off-by-one
    # that `check-provider-count.py` documents as.
    ids = re.findall(
        r"^\s*(?:pub\s+)?(\w+)\s*:\s*\w*Provider\s*,", fields.group(1), re.MULTILINE
    )
    if ids != NATIVE:
        raise SpliceError(
            f"ProviderRegistry adapter fields {ids} do not match NATIVE {NATIVE}. "
            "NATIVE also drives the dashboard dropdown, so the two must move "
            "together; update this file in the same change as the struct."
        )

    arms = re.search(r"let native = match model \{(.*?)\n\s*\};", mod_src, re.DOTALL)
    if not arms:
        raise SpliceError(
            "could not locate the `let native = match model {` arms in "
            f"{MOD_RS.relative_to(ROOT)} — no prefix column can be derived."
        )
    prefixes: dict[str, list[str]] = {}
    for guard, pid in re.findall(r'm if (.+?) => Some\("(\w+)"\)', arms.group(1)):
        prefixes[pid] = re.findall(r'starts_with\("([^"]+)"\)', guard)

    envs_src = re.search(
        r"fn env_var_for_provider_id\b.*?match provider_id \{(.*?)\n\s*other\s*=>",
        mod_src,
        re.DOTALL,
    )
    if not envs_src:
        raise SpliceError(
            "could not locate the `env_var_for_provider_id` match arms in "
            f"{MOD_RS.relative_to(ROOT)} — no credential column can be derived."
        )
    envs = dict(
        re.findall(r'"([a-z0-9._-]+)"\s*=>\s*"([A-Z0-9_]+)"', envs_src.group(1))
    )

    out: list[tuple[str, list[str], str]] = []
    for pid in ids:
        if not prefixes.get(pid) or not envs.get(pid):
            raise SpliceError(
                f"native adapter `{pid}` has no model prefix and/or no credential env "
                "var in mod.rs. Publishing a blank cell would tell a customer the "
                "adapter needs neither."
            )
        out.append((pid, prefixes[pid], envs[pid]))
    return out


def md_text(s: str) -> str:
    """Escape a free-text cell so it is inert in Markdown AND in MDX.

    `<` is the one that matters: outside a code span MDX reads it as a JSX tag
    open and drops the whole page with a 404 that still shows in the nav
    (B-150). The catalog carries none today; escaping means a label that
    acquires one later cannot take the docs site down.
    """
    return (
        s.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("|", "\\|")
    )


def md_code(s: str) -> str:
    """A cell rendered as inline code. Backticks make MDX treat it as literal."""
    if "`" in s:
        raise SpliceError(
            f"catalog value {s!r} contains a backtick and cannot be a code span"
        )
    return "`" + s.replace("|", "\\|") + "`"


def prefix_cell(prefixes: list[str]) -> str:
    """The model prefixes, exactly as the router matches them.

    Rendered verbatim — no trailing `*`. The router does `starts_with`, not glob
    matching, and decorating a prefix with a wildcard it does not support is a
    claim the code does not make.
    """
    return " · ".join(md_code(p) for p in prefixes)


def render_doc_body(
    rows: list[list[str]], native: list[tuple[str, list[str], str]]
) -> str:
    """The enumeration both pages carry, byte-identical between them.

    Only headings and tables live in here. Every sentence explaining them stays
    outside the markers, hand-written and per-page, so this function never has
    an opinion about a page's voice.
    """
    lines = [
        "### Native adapters",
        "",
        "| Provider | ID | Model prefixes | Credential env var |",
        "|---|---|---|---|",
    ]
    for pid, prefixes, env in native:
        lines.append(
            f"| {md_text(NATIVE_LABELS.get(pid, pid))} | {md_code(pid)} "
            f"| {prefix_cell(prefixes)} | {md_code(env)} |"
        )
    lines += [
        "",
        "### OpenAI-compatible catalog",
        "",
        "| Provider | ID | Default base URL | Base-URL override | API key env var | Model prefixes |",
        "|---|---|---|---|---|---|",
    ]
    for pid, label, base, base_env, key_env, prefixes in sorted(
        rows, key=lambda r: (r[1].lower(), r[0])
    ):
        # An empty `api_key_env` is Ollama, which is local and has no key to
        # send. Rendering an empty cell would read as "we forgot".
        key = md_code(key_env) if key_env else "_none — local_"
        lines.append(
            f"| {md_text(label)} | {md_code(pid)} | {md_code(base)} | {md_code(base_env)} "
            f"| {key} | {prefix_cell(prefixes.split(','))} |"
        )
    return "\n".join(lines)


def doc_markers(path: Path) -> tuple[str, str]:
    """The marker pair for one page's format.

    `.md` takes an HTML comment. `.mdx` CANNOT: MDX parses `<!--` as JSX and
    refuses the page, so the Mintlify tree uses the MDX expression comment
    `{/* … */}` that Mintlify documents. Neither form contains a `<` followed by
    a letter, so `check-docs-site.py`'s bare-`<` scan stays green on both.
    """
    if path.suffix == ".mdx":
        return (f"{{/* {DOC_BEGIN} */}}", f"{{/* {DOC_END} */}}")
    return (f"<!-- {DOC_BEGIN} -->", f"<!-- {DOC_END} -->")


def splice(text: str, begin: str, end: str, body: str) -> str:
    """Replace what is between the markers, leaving everything else byte-identical.

    Refuses anything but exactly one well-ordered pair. A missing marker is the
    interesting case: silently appending, or silently doing nothing, is how a
    page keeps its stale table while the generator reports success.
    """
    if text.count(begin) != 1 or text.count(end) != 1:
        raise SpliceError(
            f"expected exactly one {begin!r} and one {end!r}; found "
            f"{text.count(begin)} and {text.count(end)}"
        )
    i, j = text.index(begin), text.index(end)
    if j < i + len(begin):
        raise SpliceError(f"{end!r} appears before {begin!r} ends")
    return text[: i + len(begin)] + "\n\n" + body + "\n" + text[j:]


def render_doc_pages(body: str) -> dict[Path, str]:
    """What each page SHOULD contain: its current text with the block re-spliced."""
    out: dict[Path, str] = {}
    for path in DOC_PAGES:
        if not path.exists():
            raise SpliceError(f"{path.relative_to(ROOT)} is missing")
        begin, end = doc_markers(path)
        out[path] = splice(path.read_text(encoding="utf-8"), begin, end, body)
    return out


def selftest() -> int:
    bad = [
        (["a", "A", "https://x.dev/v1", "A_BASE_URL", "A_KEY", "a/"], "/v1"),
        (["b", "B", "https://x.dev", "B_BASE_URL", "B_KEY", "llama"], None),
        (["c", "C", "https://x.dev", "C_BASE_URL", "C_KEY", "llama"], "bare prefix"),
        (["A!", "X", "https://x.dev", "X_BASE_URL", "X_KEY", "x/"], "not [a-z0-9"),
        (["d", "D", "ftp://x.dev", "D_BASE_URL", "D_KEY", "d/"], "neither https"),
    ]
    ok = True
    e = check_rows([bad[0][0]])
    print(
        f"  {'✓' if any('/v1' in x for x in e) else '✗'} a base_url ending in /v1 is REFUSED"
    )
    ok &= any("/v1" in x for x in e)
    e = check_rows([bad[1][0], bad[2][0]])
    print(
        f"  {'✓' if any('bare prefix' in x for x in e) else '✗'} two providers claiming one bare prefix are REFUSED"
    )
    ok &= any("bare prefix" in x for x in e)
    e = check_rows([bad[3][0]])
    print(
        f"  {'✓' if any('not [a-z0-9' in x for x in e) else '✗'} a non-slug provider id is REFUSED"
    )
    ok &= any("not [a-z0-9" in x for x in e)
    e = check_rows([bad[4][0]])
    print(
        f"  {'✓' if any('neither https' in x for x in e) else '✗'} a non-https base_url is REFUSED"
    )
    ok &= any("neither https" in x for x in e)
    e = check_rows([["e", "E", "https://x.dev", "E_BASE_URL", "E_KEY", "e/"]])
    print(
        f"  {'✓' if not e else '✗'} a WELL-FORMED row passes (the check is not vacuous)"
    )
    ok &= not e

    # ── the doc splice. Each line below is a way the published table could go
    # stale while this script still reported success.
    body = "| generated |"
    page = "prose above\n<!-- B -->\n\n| stale |\n<!-- E -->\nprose below\n"
    fresh = splice(page, "<!-- B -->", "<!-- E -->", body)
    hit = body in fresh and "| stale |" not in fresh
    hit &= fresh.startswith("prose above\n") and fresh.endswith("prose below\n")
    print(
        f"  {'✓' if hit else '✗'} a STALE block is replaced and the prose around it is untouched"
    )
    ok &= hit

    try:
        splice("a page with no markers at all\n", "<!-- B -->", "<!-- E -->", body)
        hit = False
    except SpliceError:
        hit = True
    print(
        f"  {'✓' if hit else '✗'} a page MISSING its markers is REFUSED, never silently skipped"
    )
    ok &= hit

    hit = splice(fresh, "<!-- B -->", "<!-- E -->", body) == fresh
    print(
        f"  {'✓' if hit else '✗'} an UP-TO-DATE page re-splices to itself (so --check is not vacuous)"
    )
    ok &= hit

    md_begin, _ = doc_markers(Path("p.md"))
    mdx_begin, _ = doc_markers(Path("p.mdx"))
    hit = (
        md_begin.startswith("<!--")
        and mdx_begin.startswith("{/*")
        and "<" not in mdx_begin
    )
    print(
        f"  {'✓' if hit else '✗'} the .mdx marker carries NO HTML comment (MDX would 404 the page)"
    )
    ok &= hit

    hit = md_text("a|b <c> &d") == "a\\|b &lt;c&gt; &amp;d"
    print(
        f"  {'✓' if hit else '✗'} a cell containing | < > & is escaped (table shift + B-150)"
    )
    ok &= hit

    try:
        parse_native_adapters("pub struct ProviderRegistry {\n    compat: Map,\n}\n")
        hit = False
    except SpliceError:
        hit = True
    print(
        f"  {'✓' if hit else '✗'} a ProviderRegistry with NO adapter fields is REFUSED"
    )
    ok &= hit

    print("selftest OK" if ok else "selftest FAILED")
    return 0 if ok else 1


def check_local() -> int:
    """Verify the checked-in artifacts agree with the checked-in CATALOG.

    **No network.** This is what the gate runs, and the distinction is the whole
    point: `--check` used to re-fetch models.dev and diff, so it went red
    whenever *they* published — a gate failing for a reason that has nothing to
    do with this repo. A gate that fails on someone else's release trains people
    to ignore it, and an ignored gate is worse than none.

    What can actually rot here is INTERNAL: `providers.tsv` is edited (or
    regenerated) and the dropdown module or the two published doc tables are not
    regenerated with it. That is a real, local, deterministic defect and it is
    exactly what this checks. Prices are not re-derived: an upstream price change
    is a REFRESH (`--refresh`), not a staleness bug.
    """
    existing = parse_existing()
    rows = [existing[k] for k in sorted(existing)]

    errs = check_rows(rows)
    if errs:
        for e in errs:
            print(f"FAIL — {e}", file=sys.stderr)
        return 1

    if not MOD_RS.exists():
        print(
            f"FAIL — {MOD_RS.relative_to(ROOT)} is missing; the native-adapter "
            "half of the doc table is derived from it.",
            file=sys.stderr,
        )
        return 1
    try:
        native = parse_native_adapters(MOD_RS.read_text(encoding="utf-8"))
        pages = render_doc_pages(render_doc_body(rows, native))
    except SpliceError as exc:
        print(f"FAIL — {exc}", file=sys.stderr)
        return 1

    stale = []
    for path, want in [(DROPDOWN, render_dropdown(rows)), *pages.items()]:
        have = path.read_text(encoding="utf-8") if path.exists() else ""
        if have != want:
            stale.append(path.relative_to(ROOT))
    if stale:
        print(
            "FAIL — stale generated file(s) vs the checked-in catalog: "
            + ", ".join(map(str, stale)),
            file=sys.stderr,
        )
        print("  run: python3 scripts/ci/build-provider-catalog.py", file=sys.stderr)
        return 1

    print(
        f"OK — {len(rows)} catalog rows + {len(NATIVE)} native adapters; "
        "dropdown and doc tables match the catalog"
    )
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--check",
        action="store_true",
        help="LOCAL consistency only, no network. What the gate runs.",
    )
    ap.add_argument("--selftest", action="store_true")
    a = ap.parse_args()
    if a.selftest:
        return selftest()
    if a.check:
        return check_local()

    existing = parse_existing()
    md, sha = fetch(SOURCE_URL)
    rows = build_rows(existing, md)

    errs = check_rows(rows)
    if errs:
        for e in errs:
            print(f"FAIL — {e}", file=sys.stderr)
        return 1

    cat, pri, drop = render(rows, sha), render_prices(md, sha), render_dropdown(rows)

    # The doc pages are spliced, not overwritten: `render_doc_pages` returns each
    # page's CURRENT text with only the marked block replaced, so a prose edit
    # outside the markers is never a staleness signal and is never clobbered.
    if not MOD_RS.exists():
        print(
            f"FAIL — {MOD_RS.relative_to(ROOT)} is missing; the native-adapter "
            "half of the doc table is derived from it.",
            file=sys.stderr,
        )
        return 1
    try:
        native = parse_native_adapters(MOD_RS.read_text(encoding="utf-8"))
        pages = render_doc_pages(render_doc_body(rows, native))
    except SpliceError as exc:
        print(f"FAIL — {exc}", file=sys.stderr)
        return 1

    CATALOG.write_text(cat, encoding="utf-8")
    PRICES.write_text(pri, encoding="utf-8")
    DROPDOWN.write_text(drop, encoding="utf-8")
    for path, text in pages.items():
        path.write_text(text, encoding="utf-8")
    n_models = sum(
        1 for l in pri.splitlines() if l and not l.startswith(("#", "provider\t"))
    )
    print(
        f"wrote {CATALOG.relative_to(ROOT)}: {len(rows)} rows "
        f"({len(rows) + len(NATIVE)} providers incl. native adapters)"
    )
    print(f"wrote {PRICES.relative_to(ROOT)}: {n_models} (provider, model) price rows")
    print(
        f"wrote {DROPDOWN.relative_to(ROOT)}: {len(rows) + len(NATIVE)} dashboard entries"
    )
    for path in pages:
        print(
            f"wrote {path.relative_to(ROOT)}: provider table "
            f"({len(native)} native + {len(rows)} catalog rows)"
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
