#!/usr/bin/env python3
"""Generate apps/web/lib/role-capabilities.generated.ts from the gateway matrix.

WHY: the role x capability matrix in crates/gateway/src/auth/capability.rs
(`MATRIX`) is the ONE authority on what each role may do. The dashboard only
mirrors it, for UI gating (the gateway still enforces). A hand-copied table
drifts silently and renders buttons that 403 on click, so the mirror is
generated and `--check` fails when it is stale.

Usage:
  build-role-capabilities.py             write the generated file
  build-role-capabilities.py --check     exit 1 if the file is stale
  build-role-capabilities.py --selftest  prove --check blocks stale, passes fresh
"""

import re
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RUST = ROOT / "crates/gateway/src/auth/capability.rs"
OUT = ROOT / "apps/web/lib/role-capabilities.generated.ts"

ROW_RE = re.compile(
    r"Row::new\(Capability::(\w+),\s*\"(\w+)\",\s*([YN]),\s*([YN]),\s*([YN]),"
    r"\s*([YN]),\s*([YN]),\s*([YN]),\s*([YN])\)"
)
ROLES = ["admin", "developer", "viewer", "billing", "unrecognised"]


def parse(rust_src: str) -> list[tuple[str, list[bool]]]:
    rows = []
    for m in ROW_RE.finditer(rust_src):
        flags = [g == "Y" for g in m.groups()[2:]]
        # columns: admin developer viewer billing unrecognised api_key master
        rows.append((m.group(2), flags[:5]))
    return rows


def render(rows: list[tuple[str, list[bool]]]) -> str:
    out = [
        "// GENERATED by scripts/ci/build-role-capabilities.py — do not edit.",
        "// Source of truth: crates/gateway/src/auth/capability.rs `MATRIX`.",
        "// UI gating only; the gateway is authoritative.",
        "",
        "export type CapabilitySlug =",
    ]
    out += [f'\t| "{slug}"' for slug, _ in rows]
    out[-1] += ";"
    out += [
        "",
        "export type RoleFlags = {",
        *[f"\t{r}: boolean;" for r in ROLES],
        "};",
        "",
        "export const ROLE_CAPABILITIES: Record<CapabilitySlug, RoleFlags> = {",
    ]
    for slug, flags in rows:
        # Multi-line, tab-indented: already biome-formatted, so a format pass is a no-op.
        out.append(f"\t{slug}: {{")
        out += [f"\t\t{r}: {str(f).lower()}," for r, f in zip(ROLES, flags)]
        out.append("\t},")
    out += [
        "};",
        "",
        'export type Role = "admin" | "developer" | "viewer" | "billing";',
        "",
        "/** WorkOS slug -> role. `owner`/`admin` -> admin; `member` is the legacy developer. */",
        "export function roleFromSlug(slug: string | null | undefined): Role | null {",
        "\tswitch (slug) {",
        '\t\tcase "owner":',
        '\t\tcase "admin":',
        '\t\t\treturn "admin";',
        '\t\tcase "developer":',
        '\t\tcase "member":',
        '\t\t\treturn "developer";',
        '\t\tcase "viewer":',
        '\t\t\treturn "viewer";',
        '\t\tcase "billing":',
        '\t\t\treturn "billing";',
        "\t\tdefault:",
        "\t\t\treturn null;",
        "\t}",
        "}",
        "",
        "/** Fail-closed: an unrecognised or absent slug gets the `unrecognised` column. */",
        "export function roleCan(",
        "\tslug: string | null | undefined,",
        "\tcapability: CapabilitySlug,",
        "): boolean {",
        "\tconst flags = ROLE_CAPABILITIES[capability];",
        "\tconst role = roleFromSlug(slug);",
        "\treturn role === null ? flags.unrecognised : flags[role];",
        "}",
        "",
    ]
    return "\n".join(out)


def generate(rust: Path) -> str:
    rows = parse(rust.read_text())
    if not rows:
        raise SystemExit(f"refusing: {rust} parsed to zero MATRIX rows")
    return render(rows)


def check(rust: Path, out: Path) -> bool:
    return out.exists() and out.read_text() == generate(rust)


def selftest() -> int:
    with tempfile.TemporaryDirectory() as d:
        d = Path(d)
        rust = d / "capability.rs"
        rust.write_text(
            'Row::new(Capability::ReadTraces, "read_traces", Y, Y, Y, N, Y, Y, Y),\n'
            'Row::new(Capability::ManageTeam, "manage_team", Y, N, N, N, N, N, N),\n'
        )
        out = d / "gen.ts"
        out.write_text("// stale\n")
        if check(rust, out):
            print("selftest FAIL: stale copy passed --check")
            return 1
        out.write_text(generate(rust))
        if not check(rust, out):
            print("selftest FAIL: fresh copy failed --check")
            return 1
        rust.write_text("// no rows here\n")
        try:
            generate(rust)
        except SystemExit as e:
            if e.code in (0, None):
                print("selftest FAIL: zero rows did not refuse")
                return 1
        else:
            print("selftest FAIL: zero rows did not refuse")
            return 1
    print("selftest OK")
    return 0


def main() -> int:
    arg = sys.argv[1] if len(sys.argv) > 1 else ""
    if arg == "--selftest":
        return selftest()
    if arg == "--check":
        if check(RUST, OUT):
            return 0
        print(f"{OUT} is stale; run scripts/ci/build-role-capabilities.py")
        return 1
    if arg:
        print(__doc__)
        return 2
    OUT.write_text(generate(RUST))
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
