//! Provider adapter layer for the Tracelane gateway.
//!
//! Each sub-module translates the universal `ChatRequest` format into the
//! provider-specific wire format, handles SSE streaming, and emits `ProviderEvent`
//! items that the gateway aggregates into a response stream.
//!
//! **Providers are a DATA FILE, not code.** `crates/gateway/providers.tsv` holds
//! every OpenAI-compatible provider — id, label, base URL, env vars, model
//! prefixes — and is generated by `scripts/ci/build-provider-catalog.py`. Six
//! native adapters (Anthropic, Google AI Studio, Google Vertex, AWS Bedrock,
//! Azure OpenAI, Cohere) remain as Rust modules because their wire format
//! genuinely differs.
//!
//! Adding a provider is one row and zero Rust. It used to be ~15 lines across
//! six files plus ~10 count and claim edits across six more, and the counts in
//! this header were themselves CI-enforced string literals — was a
//! doc-comment miscount that leaked to public marketing. There is no count in
//! this comment any more, deliberately: the number is `catalog::providers()`
//! plus six, and a comment nobody checks is a claim waiting to rot.

// Prefix data is shared by the canonical match and the settings inventory.
const ANTHROPIC_PREFIXES: &[&str] = &["claude", "anthropic/"];
const VERTEX_PREFIXES: &[&str] = &["vertex/"];
const GOOGLE_PREFIXES: &[&str] = &["gemini", "google/"];
const BEDROCK_PREFIXES: &[&str] = &["bedrock/"];
const AZURE_PREFIXES: &[&str] = &["azure/"];
// D9/OG-06: `rerank-` routes Cohere's rerank models (`rerank-v3.5`, …) to its native adapter.
const COHERE_PREFIXES: &[&str] = &["command", "cohere/", "rerank-"];
pub const NATIVE_PREFIXES: &[(&str, &[&str])] = &[
    ("anthropic", ANTHROPIC_PREFIXES),
    ("vertex", VERTEX_PREFIXES),
    ("google", GOOGLE_PREFIXES),
    ("bedrock", BEDROCK_PREFIXES),
    ("azure", AZURE_PREFIXES),
    ("cohere", COHERE_PREFIXES),
];

pub mod catalog;

use anyhow::Result;
use async_stream::try_stream;
use futures::Stream;
use std::pin::Pin;
use tracing::instrument;

/// SB (security re-review round 2, 2026-10-05): marks an error DERIVED FROM THE TENANT'S
/// CREDENTIAL — parsing it, or exchanging it for a token (Vertex's OAuth2 exchange). Such
/// a failure is evidence about that credential, never about the provider, so the breaker
/// feeds it to that credential only (`server::transport_outcome`). Attached as anyhow
/// CONTEXT carrying the error's own message, so `Display`, `downcast_ref` of the inner
/// error (`ProviderHttpError` for the 401 mapping) and the source chain are unchanged.
#[derive(Debug)]
pub struct CredentialDerived(String);

impl std::fmt::Display for CredentialDerived {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for CredentialDerived {}

/// Mark `err` as credential-derived ([`CredentialDerived`]).
pub(crate) fn credential_derived(err: anyhow::Error) -> anyhow::Error {
    let message = err.to_string();
    err.context(CredentialDerived(message))
}

/// An upstream provider returned a non-success HTTP status.
///
/// Carries the status code so the gateway can distinguish an **auth rejection**
/// (401/403 → the tenant's BYOK provider key was rejected; surface
/// `provider_key_rejected`) from an **availability** failure (5xx / timeout →
/// 502). The upstream response BODY is deliberately NOT carried — provider
/// 401/403 bodies routinely echo the credential (security.md /),
/// so only the structured status survives.
///
/// Adapters return this (via `anyhow`) on a non-2xx upstream response; the chat
/// handler recovers it with `downcast_ref::<ProviderHttpError>()`.
///
/// (See also [`CredentialDerived`]: a `ProviderHttpError` produced while exchanging a
/// tenant's credential — e.g. Vertex's token endpoint — is wrapped in it.)
#[derive(Debug, thiserror::Error)]
#[error("{provider} upstream error: status {status}")]
pub struct ProviderHttpError {
    pub provider: &'static str,
    pub status: u16,
    /// Machine-readable upstream reason token (e.g. `API_KEY_INVALID`), when the
    /// provider supplies one AND it passes [`safe_reason`].
    ///
    /// A status code alone is not enough. Google answers an invalid/retired
    /// API key with **400 `INVALID_ARGUMENT` / `API_KEY_INVALID`** — verified live
    /// 2026-07-17 — not 401. A bare 400 is ambiguous (malformed request vs dead
    /// key), so without the reason we cannot tell a customer their key died, and
    /// it surfaces as an opaque 502 that reads as OUR outage.
    ///
    /// Never the upstream `message`: that is free text, and `security.md`
    /// holds that provider error bodies can echo the credential. Only a validated
    /// enum-shaped token gets in here — see [`safe_reason`].
    pub reason: Option<String>,
    /// `OG-03` §3.4. The upstream's own `error.message`, SCRUBBED and TRUNCATED, for a
    /// 4xx that is not an authentication failure — so "Unsupported parameter:
    /// max_tokens" reaches the caller instead of an unexplained failure. Built ONLY by
    /// [`ProviderHttpError::from_response`], which is the single place that decides
    /// whether a body may be relayed; `None` for 401/403/407, for every 5xx, and for
    /// anything [`ProviderHttpError::is_auth_rejection`] treats as a key problem.
    pub message: Option<String>,
    /// `OG-10`. The upstream's own `Retry-After`, parsed (delta-seconds or HTTP-date) and
    /// clamped by [`retry_after_from`]; `None` when absent or garbage. Read in the
    /// adapter's non-success branch BEFORE the body, and used in two places: the retry
    /// loop honours it (or declines to retry when it does not fit the budget), and the
    /// client response relays it so the caller's own backoff works.
    pub retry_after: Option<std::time::Duration>,
}

/// Upstream statuses whose body is NEVER relayed: the credential was rejected (the
/// body routinely echoes it), or the upstream itself failed (5xx detail is internal).
const fn body_is_relayable(status: u16) -> bool {
    status >= 400 && status < 500 && status != 401 && status != 403 && status != 407
}

/// Pull the human message out of a provider error body and make it safe to relay.
///
/// Reads `error.message`, then a top-level `message`, then a string `error` (xAI /
/// Cohere / Bedrock shapes). Then, in this order: every occurrence of the tenant's own
/// key is removed (a verbatim echo of the exact credential is the worst leak and the
/// one pattern-based scrubbing could miss), `tracelane_shared::redact::scrub` removes
/// key-shaped strings, and the result is cut to `max_chars` characters with `…`.
///
/// `max_chars == 0` — the fail-closed reading of an unparseable policy table —
/// relays nothing.
#[must_use]
pub(crate) fn provider_message_from_body(
    body: &str,
    api_key: &str,
    max_chars: usize,
) -> Option<String> {
    if max_chars == 0 {
        return None;
    }
    let v: serde_json::Value = serde_json::from_str(body).ok()?;
    let raw = v
        .get("error")
        .and_then(|e| e.get("message"))
        .and_then(serde_json::Value::as_str)
        .or_else(|| v.get("message").and_then(serde_json::Value::as_str))
        .or_else(|| v.get("error").and_then(serde_json::Value::as_str))?;
    let mut text = raw.to_owned();
    if !api_key.is_empty() {
        text = text.replace(api_key, "[REDACTED]");
    }
    let scrubbed = tracelane_shared::redact::scrub(text.as_bytes());
    let text = String::from_utf8_lossy(&scrubbed).trim().to_owned();
    if text.is_empty() {
        return None;
    }
    if text.chars().count() > max_chars {
        let mut cut: String = text.chars().take(max_chars.saturating_sub(1)).collect();
        cut.push('…');
        return Some(cut);
    }
    Some(text)
}

/// Accept an upstream reason token only if it is structurally incapable of
/// carrying a credential: SHOUTY_SNAKE_CASE, `[A-Z0-9_]`, ≤64 chars.
///
/// This is the security boundary that lets us read anything at all out of a
/// provider error body. An API key (`AIzaSy…`, `AQ.Ab…`, `sk-…`) is mixed-case
/// and/or punctuated, so it cannot satisfy this shape — the guard fails closed on
/// anything surprising rather than trusting the provider's field naming.
#[must_use]
pub fn safe_reason(raw: &str) -> Option<String> {
    let ok = !raw.is_empty()
        && raw.len() <= 64
        && raw
            .bytes()
            .all(|b| b.is_ascii_uppercase() || b.is_ascii_digit() || b == b'_');
    ok.then(|| raw.to_owned())
}

/// Extract a safe reason token from a provider's JSON error body.
///
/// Reads ONLY structured tokens — Google/GCP shape:
/// `error.details[].reason`, falling back to `error.status`. The free-text
/// `error.message` is never touched. Returns `None` for any body we don't
/// recognise, so a provider that changes its shape degrades to today's behaviour
/// (status-only) rather than leaking or misreporting.
#[must_use]
pub fn reason_from_body(body: &str) -> Option<String> {
    let v: serde_json::Value = serde_json::from_str(body).ok()?;
    let err = v.get("error")?;
    if let Some(details) = err.get("details").and_then(|d| d.as_array()) {
        for d in details {
            if let Some(r) = d.get("reason").and_then(|r| r.as_str())
                && let Some(safe) = safe_reason(r)
            {
                return Some(safe);
            }
        }
    }
    err.get("status")
        .and_then(|s| s.as_str())
        .and_then(safe_reason)
}

impl ProviderHttpError {
    /// The one constructor adapters use for a non-2xx response.
    ///
    /// `message` is attached only when the status is a relayable 4xx AND the error is
    /// not an auth rejection (Google answers a dead key with a 400 whose body names
    /// the key) — the order matters, so the decision is made on the finished error.
    #[must_use]
    pub fn from_response(
        provider: &'static str,
        status: u16,
        reason: Option<String>,
        body: &str,
        api_key: &str,
    ) -> Self {
        let mut err = Self {
            provider,
            status,
            reason,
            message: None,
            retry_after: None,
        };
        if body_is_relayable(status) && !err.is_auth_rejection() {
            err.message = provider_message_from_body(
                body,
                api_key,
                translation_policy::limits().provider_message_max_chars,
            );
        }
        err
    }

    /// Attach the upstream's `Retry-After` (`OG-10`); see [`retry_after_from`].
    #[must_use]
    pub fn with_retry_after(mut self, retry_after: Option<std::time::Duration>) -> Self {
        self.retry_after = retry_after;
        self
    }

    /// True when the upstream rejected the credential itself — the tenant's key is
    /// wrong/expired/retired, not a transient outage. Drives the
    /// `provider_key_rejected` response (/ GW-SPAN-002).
    ///
    /// Two shapes:
    ///   - **401 / 403** — the classic status-level rejection.
    ///   - **400 + a key-invalid reason** — Google's shape. A bare 400 is
    ///     NOT a rejection (it is usually a malformed request); only a 400 whose
    ///     reason names the key qualifies.
    #[must_use]
    pub fn is_auth_rejection(&self) -> bool {
        if matches!(self.status, 401 | 403) {
            return true;
        }
        self.status == 400
            && self
                .reason
                .as_deref()
                .is_some_and(|r| r.contains("API_KEY") || r.contains("CREDENTIAL"))
    }

    /// True when the upstream rate-limited or exhausted quota (429). The caller
    /// should surface 429 — telling a caller "provider unavailable" when they are
    /// simply over quota sends them debugging the wrong system.
    #[must_use]
    pub fn is_rate_limited(&self) -> bool {
        self.status == 429
    }

    /// True when the status is an UPSTREAM fault — a breaker trip input (ADR-036 as
    /// amended 2026-10-03: timeouts and 5xx).
    ///
    /// F4, 2026-10-03: 429 is NOT one. Under BYOK a 429 is the tenant's OWN account
    /// quota — the same "one tenant's key opens the circuit for everyone" shape as the
    /// 4xx below, observed live (a free-tier Mistral key's 429s → `503
    /// upstream_circuit_open` for the whole process). The tenant still gets its 429 and
    /// `retry-after`; the retry loop honours it.
    ///
    /// SRE audit finding 38, 2026-09-04. A 401/403/404/400 blames the CALLER's key,
    /// model or body, not the provider's health — and `CircuitBreaker` is keyed
    /// `(provider, region)` with **no tenant dimension** (`circuit_breaker.rs`
    /// `DashMap<(String, String), _>`, region hardcoded `"default"` at both call
    /// sites, one instance per process). So counting one tenant's dead BYOK key as a
    /// provider fault trips the breaker for EVERY tenant on that provider. The
    /// breaker was fed `provider_result.is_ok()`, which is true of any error at all.
    #[must_use]
    pub fn is_upstream_fault(&self) -> bool {
        self.status >= 500
    }

    /// True when the upstream says the model does not exist (404). Distinct from
    /// an outage: the caller must change their model string, not retry.
    /// Observed live 2026-07-17 — AI Studio 404s models "no longer available to
    /// new users", which as a 502 read as a Tracelane outage.
    #[must_use]
    pub fn is_model_not_found(&self) -> bool {
        self.status == 404
    }

    /// True for any upstream **4xx we could not classify** with the three
    /// specific predicates above.
    ///
    /// This is deliberately **NOT** a reclassification of 400 as an auth
    /// rejection. xAI answers an invalid key with `400 {"code":
    /// "invalid-argument", "error":"Incorrect API key provided."}` — verified
    /// live 2026-07-28 — but a malformed payload is *also* a 400, and calling
    /// that a key problem sends the caller to rotate a perfectly good key. We
    /// cannot tell the two apart without reading the free-text body, which
    /// `security.md` forbids propagating (it can echo the credential).
    ///
    /// So we assert only what the status alone proves: the upstream rejected
    /// the **request**, which is a client-class problem, not a Tracelane
    /// outage. The caller gets a 4xx naming the upstream status and both
    /// candidate causes — strictly more honest than the `502 provider
    /// unavailable` this used to fall through to, which blamed us.
    ///
    /// The parsed path is untouched: 401/403 and Google's
    /// `400 API_KEY_INVALID` still resolve to `provider_key_rejected` above and
    /// never reach here.
    #[must_use]
    pub fn is_unclassified_client_error(&self) -> bool {
        (400..500).contains(&self.status)
            && !self.is_auth_rejection()
            && !self.is_rate_limited()
            && !self.is_model_not_found()
    }
}

#[cfg(test)]
mod provider_http_error_tests {
    use super::ProviderHttpError;

    use super::{reason_from_body, safe_reason};

    fn err(status: u16, reason: Option<&str>) -> ProviderHttpError {
        ProviderHttpError {
            provider: "openai",
            status,
            reason: reason.map(str::to_owned),
            message: None,
            retry_after: None,
        }
    }

    #[test]
    fn auth_rejection_covers_401_403() {
        for s in [401u16, 403] {
            assert!(err(s, None).is_auth_rejection());
        }
        // Availability / rate-limit failures are NOT auth rejections — they must
        // never be reported to the user as "provider key rejected".
        for s in [404u16, 408, 429, 500, 502, 503] {
            assert!(!err(s, None).is_auth_rejection());
        }
    }

    /// Google answers an invalid/retired API key with 400 API_KEY_INVALID,
    /// NOT 401 — verified live 2026-07-17. Google retires ALL classic `AIza` keys
    /// in Sept 2026, so without this every affected customer would get an opaque
    /// 502 reading as a Tracelane outage.
    #[test]
    fn bare_400_is_not_a_rejection_but_400_with_key_reason_is() {
        // A bare 400 is a malformed request — telling the user their key is bad
        // would send them to rotate a perfectly good credential.
        assert!(!err(400, None).is_auth_rejection());
        assert!(!err(400, Some("INVALID_ARGUMENT")).is_auth_rejection());
        // ...but a 400 that names the key IS a rejection.
        assert!(err(400, Some("API_KEY_INVALID")).is_auth_rejection());
        assert!(err(400, Some("API_KEY_EXPIRED")).is_auth_rejection());
        assert!(err(400, Some("CREDENTIAL_MISSING")).is_auth_rejection());
    }

    /// An unclassified upstream 4xx must stop being reported as a 502
    /// outage — but must NOT be reclassified as an auth rejection either, or a
    /// malformed payload would send the caller to rotate a good key.
    #[test]
    fn unclassified_4xx_is_client_class_but_never_an_auth_rejection() {
        // xAI's dead-key shape (400, unparseable reason) and a genuinely
        // malformed request are INDISTINGUISHABLE here — both land in this
        // bucket, and neither claims to know which it is.
        for s in [400u16, 402, 409, 413, 415, 422, 451] {
            let e = err(s, None);
            assert!(
                e.is_unclassified_client_error(),
                "{s} should be client-class"
            );
            assert!(!e.is_auth_rejection(), "{s} must NOT claim the key is bad");
        }
    }

    /// The three parsed paths keep their own handling — this bucket is strictly
    /// the fallback, so behaviour is unchanged.
    #[test]
    fn classified_statuses_never_fall_into_the_unclassified_bucket() {
        for e in [
            err(401, None),
            err(403, None),
            err(429, None),
            err(404, None),
            err(400, Some("API_KEY_INVALID")), // parsed path
        ] {
            assert!(!e.is_unclassified_client_error());
        }
    }

    /// 5xx is a real outage and must stay a 502 — the fallback below this bucket.
    #[test]
    fn server_errors_are_not_client_class() {
        for s in [500u16, 502, 503, 504] {
            assert!(!err(s, None).is_unclassified_client_error());
        }
    }

    #[test]
    fn rate_limit_and_model_not_found_are_distinct_from_outage() {
        assert!(err(429, None).is_rate_limited());
        assert!(err(404, None).is_model_not_found());
        // A real outage is neither — it must stay a 502.
        for s in [500u16, 502, 503] {
            assert!(!err(s, None).is_rate_limited());
            assert!(!err(s, None).is_model_not_found());
            assert!(!err(s, None).is_auth_rejection());
        }
    }

    /// THE SECURITY BOUNDARY: `safe_reason` is what lets us read anything at all
    /// out of a provider error body (which `security.md` says can echo the
    /// credential). Every real key shape must be structurally incapable of passing.
    #[test]
    fn safe_reason_cannot_admit_a_credential() {
        for key in [
            "AIzaSyAbCdEfGhIjKlMnOpQrStUvWxYz0123456789", // classic Google (mixed case)
            "AQ.AbFAKEauthkeyshapedvaluefortesting00000", // modern Google (dot)
            "sk-proj-abcdefghijklmnopqrstuvwxyz",         // OpenAI (dashes, lowercase)
            "sk-ant-api03-abcdefghijklmnop",              // Anthropic
            "tlane_abcdefghijklmnopqrstuvwxyz012345",     // our own
            "-----BEGIN PRIVATE KEY-----",                // PEM
        ] {
            assert!(
                safe_reason(key).is_none(),
                "credential-shaped value must never pass safe_reason: {key}"
            );
        }
        // Real reason tokens do pass.
        for r in ["API_KEY_INVALID", "RESOURCE_EXHAUSTED", "INVALID_ARGUMENT"] {
            assert_eq!(safe_reason(r).as_deref(), Some(r));
        }
        // Bounded: no unbounded blob gets in.
        assert!(safe_reason(&"A".repeat(65)).is_none());
        assert!(safe_reason("").is_none());
    }

    /// Pinned to the REAL body Google returned for an invalid key (captured live
    /// 2026-07-17) — not a body I imagined.
    #[test]
    fn extracts_reason_from_the_real_google_error_body() {
        let body = r#"{"error":{"code":400,
            "message":"API key not valid. Please pass a valid API key.",
            "status":"INVALID_ARGUMENT",
            "details":[{"@type":"type.googleapis.com/google.rpc.ErrorInfo",
                        "reason":"API_KEY_INVALID","domain":"googleapis.com",
                        "metadata":{"service":"generativelanguage.googleapis.com"}}]}}"#;
        assert_eq!(reason_from_body(body).as_deref(), Some("API_KEY_INVALID"));
    }

    #[test]
    fn reason_falls_back_to_status_then_to_none() {
        // No details[] → fall back to error.status.
        let s = r#"{"error":{"code":429,"message":"quota","status":"RESOURCE_EXHAUSTED"}}"#;
        assert_eq!(reason_from_body(s).as_deref(), Some("RESOURCE_EXHAUSTED"));
        // Unrecognised shapes degrade to None (status-only mapping), never panic.
        assert!(reason_from_body(r#"{"error":"invalid_grant"}"#).is_none()); // OAuth shape
        assert!(reason_from_body(r#"{"error":{"message":"boom"}}"#).is_none());
        assert!(reason_from_body("not json").is_none());
        assert!(reason_from_body("").is_none());
    }

    /// The free-text `message` must never become a reason — it is the field most
    /// likely to echo a credential.
    #[test]
    fn message_is_never_used_as_a_reason() {
        let body = r#"{"error":{"code":400,"message":"key AIzaSyLEAKED0000000000000000000000000000 is bad"}}"#;
        let r = reason_from_body(body);
        assert!(r.is_none(), "message must not leak into reason: {r:?}");
    }
}

pub mod anthropic;
pub mod azure;
pub mod bedrock;
pub mod cohere;
pub mod failover;
pub mod google;
pub mod openai;
pub(crate) mod responses_bridge;
pub mod retry_after;
pub(crate) mod sse_lines;
pub(crate) mod translation_policy;
pub mod vertex;

// `all(test, debug_assertions)`, NOT just `test`: smoke_tests calls the
// loopback bypass (`ssrf_guard::set_loopback_bypass_for_tests`), which is
// `#[cfg(debug_assertions)]` (bypass is debug-only; release hard-denies). Under
// `cargo bench`/`cargo test --release` the profile is release (debug_assertions
// off) while cfg(test) is on — so a plain `#[cfg(test)]` gate compiles the
// caller without the callee → E0425. Keeping the security invariant means
// excluding smoke_tests from any non-debug build.
#[cfg(all(test, debug_assertions))]
mod smoke_tests;

// Behavioral E2E per adapter: full stream collection + end-state
// assertions (content assembly, tool-call deltas, usage, wire cost). Same
// cfg gate as smoke_tests (debug-only loopback SSRF bypass —).
#[cfg(all(test, debug_assertions))]
mod behavioral_tests;

// `OG-90` (RCA control C1): the adapter no-silent-drop matrix — every native adapter ×
// every `ChatRequest` field × every `ContentPart` is either on the wire the real adapter
// sends, or refused with a 400 that names it. Same cfg gate (debug-only loopback bypass).
#[cfg(all(test, debug_assertions))]
mod conformance_tests;

pub use anthropic::AnthropicProvider;
pub use azure::AzureOpenAiProvider;
pub use bedrock::BedrockProvider;
pub use cohere::CohereProvider;
pub use google::GoogleProvider;
pub use openai::{
    // GWY-26: the OpenAI embeddings wire shape the handler consumes, owned by
    // the adapter that speaks that format (see the block at the end of
    // `openai.rs`). The response-side shapes stay in `openai.rs`; nothing
    // outside it names them.
    EmbeddingsRequest,
    OpenAiProvider,
};
pub use retry_after::retry_after_from;
pub use vertex::VertexProvider;

use tracelane_shared::{ChatRequest, ChatResponse, TenantId};

/// Why the model stopped, in the OpenAI `finish_reason` vocabulary.
///
/// # B-354
///
/// The gateway used to hardcode `"stop"` at every site that emits a
/// `finish_reason`, so a client running the standard OpenAI tool loop — keep
/// calling while `finish_reason == "tool_calls"` — could not run it through the
/// gateway at all, and a truncated answer was indistinguishable from a complete
/// one. Providers all report this; nothing carried it across the seam.
///
/// It is an enum rather than a `String` so the value on the wire can only ever
/// be one of OpenAI's four, whatever a provider spells its own stop reason.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FinishReason {
    Stop,
    Length,
    ToolCalls,
    ContentFilter,
}

impl FinishReason {
    /// The OpenAI wire spelling.
    #[must_use]
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Stop => "stop",
            Self::Length => "length",
            Self::ToolCalls => "tool_calls",
            Self::ContentFilter => "content_filter",
        }
    }

    /// Anthropic's `message_delta.delta.stop_reason`.
    ///
    /// `None` for a value we do not recognise — an unknown stop reason falls
    /// back to the derived default rather than being forwarded as a word no
    /// OpenAI client knows.
    #[must_use]
    pub fn from_anthropic_stop_reason(reason: &str) -> Option<Self> {
        match reason {
            "tool_use" => Some(Self::ToolCalls),
            "max_tokens" => Some(Self::Length),
            "end_turn" | "stop_sequence" => Some(Self::Stop),
            "refusal" => Some(Self::ContentFilter),
            _ => None,
        }
    }

    /// An OpenAI-family provider's own `choices[].finish_reason`, passed
    /// through. `function_call` is the pre-2023 spelling of `tool_calls` and
    /// some compatible hosts still emit it.
    #[must_use]
    pub fn from_openai_finish_reason(reason: &str) -> Option<Self> {
        match reason {
            "stop" => Some(Self::Stop),
            "length" => Some(Self::Length),
            "tool_calls" | "function_call" => Some(Self::ToolCalls),
            "content_filter" => Some(Self::ContentFilter),
            _ => None,
        }
    }
}

/// A streaming response event from a provider adapter.
#[derive(Debug)]
pub enum ProviderEvent {
    /// Incremental text token (also referred to as StreamChunk in eval specs)
    StreamChunk { delta: String },
    /// Incremental tool call argument chunk
    ToolCallDelta {
        index: usize,
        id: Option<String>,
        name: Option<String>,
        input_delta: String,
    },
    /// Incremental thinking/reasoning token (Anthropic extended thinking,
    /// Gemini thoughts). Parsed by two adapters and, today, FORWARDED BY NO
    /// CONSUMER — the OpenAI wire has no standard field for it and the recorder
    /// does not capture reasoning text. Filed as B-392 (2026-09-12); the field
    /// stays so the adapters keep parsing what a consumer will need.
    ThinkingDelta {
        #[allow(dead_code)]
        delta: String,
    },
    /// Token usage update
    UsageUpdate {
        input_tokens: u32,
        output_tokens: u32,
        cache_read: Option<u32>,
        cache_creation: Option<u32>,
        /// Upstream-reported request cost in USD. `Some` only when the
        /// provider puts a cost on the wire (e.g. OpenRouter's `usage.cost`);
        /// `None` otherwise — we never fabricate a price from a hardcoded
        /// model→price table. Threaded to the span as `gen_ai.usage.cost`.
        cost_usd: Option<f64>,
        /// RI-05 / M11: reasoning ("thinking") output tokens, when the
        /// provider reports them SEPARATELY from `output_tokens` — OpenAI's
        /// `usage.completion_tokens_details.reasoning_tokens`, Gemini's
        /// `usageMetadata.thoughtsTokenCount`. `output_tokens` above stays
        /// INCLUSIVE of these (cost/billing parity, unchanged); this is the
        /// same total broken out for `gen_ai.usage.reasoning.output_tokens`.
        /// `None` when the provider sent no such field — never a fabricated
        /// zero. Anthropic has no such field on the wire and always reports
        /// `None` here.
        reasoning: Option<u32>,
    },
    /// The provider's own stop reason, normalised (B-354). Emitted at most
    /// once per stream, before the stream ends. Consumers that do not care
    /// fall through their `_ => {}` arm, which is why this is a new variant
    /// rather than a field bolted onto `UsageUpdate`.
    Finish { reason: FinishReason },
    /// `OBS-53`. Per-chunk token logprobs, OpenAI-compatible wire only.
    ///
    /// **A new variant is SILENTLY DROPPED by every existing consumer**, and
    /// that is not the reassurance the `Finish` comment above makes it sound
    /// like: all twelve match sites on this enum carry a catch-all, so the
    /// compiler will NOT point at the places that need wiring. B-353 shipped
    /// exactly that way (`server.rs`, `ToolCallAccumulator`'s doc). The two
    /// consumers that matter were therefore wired BY HAND: the SSE loop and the
    /// buffered fold, both in `server.rs`. If you add a third stream consumer,
    /// nothing will remind you.
    LogprobsDelta { logprobs: Vec<f64> },
    /// RI-05 / B-444 (2026-09-19): the provider's identity claims about the
    /// response — its own `id`, the model string it says it SERVED, and (OpenAI
    /// wire) `system_fingerprint`. Emitted from the first frame that carries them
    /// (OpenAI-compatible SSE chunks carry `id`/`model` on every chunk; Anthropic's
    /// `message_start.message`; Bedrock's whole `ChatResponse`). Consumers keep the
    /// FIRST and ignore later ones.
    ///
    /// **Silently dropped by every match site that carries a catch-all** — the same
    /// warning as `LogprobsDelta` above. The two consumers that matter, the SSE loop
    /// (`server/stream.rs`) and the buffered fold (`server/buffered.rs`), were wired
    /// by hand; `prompt_eval.rs` and `online_eval.rs` do not record spans from these
    /// events and need nothing.
    ResponseMeta {
        id: Option<String>,
        model: Option<String>,
        system_fingerprint: Option<String>,
    },
    /// Final non-streaming response (used for non-streaming calls)
    Done { response: ChatResponse },
}

pub type ProviderStream = Pin<Box<dyn Stream<Item = Result<ProviderEvent>> + Send>>;

// B-390 (2026-09-12): the `ProviderAdapter` trait that used to sit here was
// DELETED — no adapter implemented it and no caller was generic over it; the
// registry dispatches by concrete type (`server::dispatch_to_provider`). It was
// the "Provider trait ✅ Done" row of the archived V1 launch status, which
// described an intention the code never took up.

/// Registry of provider adapters: **6 native + every row in `providers.tsv`**.
///
/// GWY-42. This used to carry one named field per OpenAI-compatible provider —
/// 29 of them, all the same type, differing only in a base URL and an id — and
/// five `match` statements keyed off those field names. Adding a provider meant
/// editing all six places plus a BYOK allowlist, a TS dropdown and three
/// CI-enforced doc-comment counts. Two shipped defects came out of that shape:
/// **** (a model dispatched to Groq while its BYOK key resolved under
/// "anthropic") and **** ("routed ≠ usable" — providers that dispatched
/// fine but could not have a key stored). Both are two lists disagreeing.
///
/// Now there is one list: `crates/gateway/providers.tsv`, parsed by
/// [`catalog`]. The native six stay as typed fields because their wire format
/// genuinely differs; everything else is a row.
///
/// The full routing table is DATA, not a comment. `catalog::provider_id_for_model`
/// resolves namespaced prefixes first, then bare prefixes longest-first — see
/// that module for why the order is derived rather than written down.
pub struct ProviderRegistry {
    // ── Dedicated adapters — genuinely different wire formats ────────────────
    pub anthropic: AnthropicProvider,
    pub google: GoogleProvider,
    /// Vertex first-party Gemini. Separate from `google` because Vertex
    /// rejects API keys (service-account OAuth only) and is the ONLY Gemini
    /// path that Google Cloud credits can pay for.
    pub vertex: VertexProvider,
    pub bedrock: BedrockProvider,
    pub azure: AzureOpenAiProvider,
    pub cohere: CohereProvider,

    /// Every OpenAI-compatible provider, keyed by catalog id. `openai` itself
    /// lives here — it was always an `OpenAiProvider`, and giving it a special
    /// field only made it look like a different kind of thing.
    compat: std::collections::HashMap<&'static str, OpenAiProvider>,
}

impl ProviderRegistry {
    /// A14: constructor is now fallible — every provider's reqwest client
    /// build is `?`-propagated rather than `expect()`-panicked, satisfying
    /// `.claude/rules/rust.md` "no unwrap/expect outside tests". Call this
    /// once at server startup and `?` the result into `Arc::new(...)`.
    pub fn new() -> anyhow::Result<Self> {
        // One `OpenAiProvider` per catalog row. `base_url()` reads the row's
        // `<PROVIDER>_BASE_URL` env override, so every provider stays
        // re-pointable at a private or self-hosted endpoint without a release —
        // the behaviour the 29 hand-written constructors had, now uniform.
        let mut compat = std::collections::HashMap::with_capacity(catalog::providers().len());
        for def in catalog::providers() {
            compat.insert(def.id, OpenAiProvider::compatible(def.base_url(), def.id)?);
        }

        Ok(Self {
            anthropic: AnthropicProvider::new()?,
            google: GoogleProvider::new()?,
            vertex: VertexProvider::new()?,
            bedrock: BedrockProvider::new()?,
            azure: AzureOpenAiProvider::new()?,
            cohere: CohereProvider::new()?,
            compat,
        })
    }

    /// The OpenAI-compatible adapter for `provider_id`, if the catalog has one.
    ///
    /// `None` means "not an OpenAI-compatible provider" — either a native
    /// adapter or an id we do not carry. Callers must distinguish those two
    /// themselves; conflating them is how a native provider gets an
    /// OpenAI-shaped request.
    #[must_use]
    pub fn compat(&self, provider_id: &str) -> Option<&OpenAiProvider> {
        self.compat.get(provider_id)
    }

    /// Point one catalog provider at a different base URL. **Tests only.**
    ///
    /// The production override is the row's `<PROVIDER>_BASE_URL` env var, read
    /// at construction. Tests cannot use that: mutating the environment is
    /// `unsafe` in edition 2024 and is banned outside `#[cfg(test)]` build
    /// scripts, and it would leak across the whole test binary. This is the
    /// narrow, compile-time-gated equivalent — it cannot exist in a release
    /// binary at all, which is the property that matters.
    #[cfg(test)]
    pub fn set_compat_base_url_for_test(
        &mut self,
        provider_id: &'static str,
        base_url: String,
    ) -> anyhow::Result<()> {
        self.compat.insert(
            provider_id,
            OpenAiProvider::compatible(base_url, provider_id)?,
        );
        Ok(())
    }

    /// Resolve the provider family ID from a model string prefix (A4).
    ///
    /// Used as the `provider_id` column in `provider_keys` so BYOK
    /// ciphertext is bound to a stable family token regardless of the
    /// specific model variant. Mirrors the match arms in
    /// `env_var_for_provider_id` — keep both in sync.
    /// The SINGLE canonical model→provider map. Returns `None` for an unmatched
    /// model —: it MUST NOT default to a provider. Defaulting would fetch
    /// that provider's key for a model the caller never meant (credential
    /// misrouting). Every consumer fail-closes on `None` with a typed
    /// `unroutable_model` error. Enforced by
    /// `scripts/ci/check-provider-mapping-single-source.py`.
    pub fn provider_id_for_model(model: &str) -> Option<&'static str> {
        // GWY-39: operator-defined `tracelane.yaml` aliases are consulted FIRST
        // and by EXACT NAME. Placing them here — inside the ONE canonical map —
        // is what makes every delegate (`provider_name_from_model`,
        // `dispatch_to_provider`, and through it `env_var_for_provider_id`) honour an alias
        // without any of them growing a second lookup.
        //
        // Cost when no `tracelane.yaml` exists (every deployment today): one
        // acquire-load, then `None`.
        if let Some(a) = crate::server::config::alias(model) {
            return Some(a.provider_id.as_str());
        }

        // The six native adapters, whose wire format is not OpenAI's. They are
        // matched BEFORE the catalog and their arms are unchanged from the
        // hand-written table — including `vertex/` ahead of `gemini`, which is
        // what keeps `vertex/gemini-2.5-pro` off the AI Studio adapter.
        //
        // No catalog row claims any of these prefixes; the
        // `native_prefixes_are_not_shadowed_by_the_catalog` test proves it, so
        // the split cannot silently start stealing traffic.
        let native = match model {
            m if ANTHROPIC_PREFIXES.iter().any(|p| m.starts_with(p)) => Some("anthropic"),
            m if VERTEX_PREFIXES.iter().any(|p| m.starts_with(p)) => Some("vertex"),
            m if GOOGLE_PREFIXES.iter().any(|p| m.starts_with(p)) => Some("google"),
            m if BEDROCK_PREFIXES.iter().any(|p| m.starts_with(p)) => Some("bedrock"),
            m if AZURE_PREFIXES.iter().any(|p| m.starts_with(p)) => Some("azure"),
            m if COHERE_PREFIXES.iter().any(|p| m.starts_with(p)) => Some("cohere"),
            _ => None,
        };
        if native.is_some() {
            return native;
        }

        // Everything else is a catalog row.: this returns `None` for an
        // unmatched model and there is NO default arm here or in the catalog —
        // defaulting would fetch some provider's key for a model the caller
        // never named. Every consumer fail-closes on `None` with a typed
        // `unroutable_model` error.
        catalog::provider_id_for_model(model)
    }

    /// The adapter for `provider_id`, when that provider speaks the
    /// OpenAI-compatible wire format (`POST {base}/v1/embeddings`,
    /// `POST {base}/v1/chat/completions`).
    ///
    /// `None` for the native adapters — Anthropic, Google, Vertex, Bedrock,
    /// Azure and Cohere each have their own request shape and their own
    /// embeddings endpoint (or none). GWY-26 dispatches embeddings through
    /// this, so a `None` is a typed refusal naming the provider, never a
    /// wrong-shape request forwarded on a guess.
    ///
    /// GWY-42: this used to be a 29-arm `match` that had to be kept in step
    /// with the struct by hand, and a provider missing from it chatted fine
    /// while its embeddings refused. It is now the same map the constructor
    /// filled, so the two cannot disagree.
    #[must_use]
    pub fn openai_compatible(&self, provider_id: &str) -> Option<&OpenAiProvider> {
        self.compat(provider_id)
    }

    /// `OG-13`: the upstream region a dispatch to `provider_id` lands in — Bedrock's AWS
    /// region, Vertex's location, Azure's resource host — so the circuit breaker keys on
    /// it instead of the literal `"default"`. Every other provider has one endpoint per
    /// process: `"default"`. Still a PROCESS setting (spec §6: no per-request region).
    #[must_use]
    pub fn upstream_region(&self, provider_id: &str) -> &str {
        match provider_id {
            "bedrock" => self.bedrock.region(),
            "vertex" => self.vertex.location(),
            "azure" => self.azure.endpoint(),
            _ => "default",
        }
    }

    /// Provider-id → API-key env-var name.
    ///
    /// Returns `""` for a provider that needs no key (Ollama is local) **and**
    /// for an id we do not carry. That conflation is deliberate and predates
    /// GWY-42: `config::is_known_provider_id` special-cases `"ollama"` and
    /// treats every other empty answer as unknown, and fail-safe is
    /// that an unrecognised id yields NO key rather than a different
    /// provider's. `catalog::api_key_env` is the typed version for callers that
    /// must tell the two apart.
    #[must_use]
    pub fn env_var_for_provider_id(provider_id: &str) -> &'static str {
        match provider_id {
            "anthropic" => "ANTHROPIC_API_KEY",
            "vertex" => "GOOGLE_VERTEX_SERVICE_ACCOUNT_JSON",
            "google" => "GOOGLE_API_KEY",
            "bedrock" => "AWS_ACCESS_KEY_ID",
            "azure" => "AZURE_OPENAI_API_KEY",
            "cohere" => "COHERE_API_KEY",
            // Every OpenAI-compatible provider, from the one catalog.
            other => catalog::api_key_env(other).unwrap_or(""),
        }
    }
}

/// A mock provider for use in eval runs and tests.
/// Never makes real network calls.
pub struct MockProvider {
    pub response_text: String,
}

impl MockProvider {
    pub fn new(response_text: impl Into<String>) -> Self {
        Self {
            response_text: response_text.into(),
        }
    }

    #[instrument(skip(self, _request, _api_key), fields(tenant_id = %tenant_id))]
    // Borrows the request: taking it by value forced the caller to
    // `.clone()`, so every benchmarked request paid for a ChatRequest copy that
    // a real dispatch never makes — the harness would attribute that clone to
    // "gateway overhead" (, verifier finding d).
    pub async fn chat_mock(
        &self,
        _request: &ChatRequest,
        _api_key: &str,
        tenant_id: &TenantId,
    ) -> Result<ProviderStream> {
        let text = self.response_text.clone();
        let stream = try_stream! {
            yield ProviderEvent::StreamChunk { delta: text };
            yield ProviderEvent::UsageUpdate {
                input_tokens: 10,
                output_tokens: 5,
                cache_read: None,
                cache_creation: None,
                cost_usd: None,
                reasoning: None,
            };
        };
        Ok(Box::pin(stream))
    }
}

#[cfg(test)]
mod model_routing_consistency_tests {
    use super::ProviderRegistry;

    /// The two id-keyed hops the hot path takes, fused for these tests. B-390
    /// deleted the production model-keyed wrapper (nothing called it); the tests
    /// below assert the composed answer, which is what a caller would observe.
    fn api_key_env_var(model: &str) -> Option<&'static str> {
        ProviderRegistry::provider_id_for_model(model)
            .map(ProviderRegistry::env_var_for_provider_id)
    }

    /// Regression: the dispatch match in `server.rs` routes
    /// `llama*` / `qwen/*` / `gemma*` to `registry.groq`, but the BYOK
    /// key-lookup functions used to default them to `anthropic` /
    /// `ANTHROPIC_API_KEY`. A stored Groq key then never resolved (401), and
    /// a stored Anthropic key would have been sent to `api.groq.com`. The
    /// key-lookup pair MUST agree with the dispatch provider for these models.
    /// The comment in `provider_id_for_model` claims no catalog row can steal a
    /// native adapter's traffic. This is that claim, executable.
    ///
    /// The split is the one new risk GWY-42 introduced: natives are matched in
    /// Rust BEFORE the catalog, so a catalog row claiming `claude` or `gemini`
    /// would be silently unreachable — and worse, a row claiming a prefix the
    /// natives DON'T cover but that overlaps one (say `command-r` vs `command`)
    /// would change which adapter, and therefore which credential, a live model
    /// string resolves to. That is the shape.
    #[test]
    fn native_prefixes_are_not_shadowed_by_the_catalog() {
        const NATIVE_PREFIXES: &[(&str, &str)] = &[
            ("claude", "anthropic"),
            ("anthropic/", "anthropic"),
            ("vertex/", "vertex"),
            ("gemini", "google"),
            ("google/", "google"),
            ("bedrock/", "bedrock"),
            ("azure/", "azure"),
            ("command", "cohere"),
            ("cohere/", "cohere"),
        ];
        for (prefix, owner) in NATIVE_PREFIXES {
            // No catalog row may claim a prefix that overlaps a native one in
            // EITHER direction: `p.starts_with(native)` would be shadowed and
            // dead; `native.starts_with(p)` would shadow the native.
            for def in super::catalog::providers() {
                for p in &def.prefixes {
                    assert!(
                        !p.starts_with(prefix) && !prefix.starts_with(p),
                        "catalog provider `{}` claims prefix `{p}`, which collides with \
                         native `{prefix}` (owned by {owner}) — one of them becomes \
                         unreachable and a model string would resolve to the wrong \
                         credential",
                        def.id
                    );
                }
            }
            // And the resolver still hands the native its own traffic.
            let model = format!("{prefix}some-model");
            assert_eq!(
                ProviderRegistry::provider_id_for_model(&model),
                Some(*owner),
                "`{model}` must still resolve to the native adapter `{owner}`"
            );
        }
    }

    #[test]
    fn groq_family_models_resolve_to_groq_not_anthropic() {
        for m in [
            "llama-3.3-70b-versatile",
            "llama-3.1-8b-instant",
            "qwen/qwen3-32b",
            "gemma2-9b-it",
        ] {
            assert_eq!(
                ProviderRegistry::provider_id_for_model(m),
                Some("groq"),
                "provider_id_for_model({m}) must be groq (dispatch routes it to registry.groq)"
            );
            assert_eq!(
                api_key_env_var(m),
                Some("GROQ_API_KEY"),
                "api_key_env_var({m}) must be GROQ_API_KEY (was defaulting to ANTHROPIC_API_KEY)"
            );
        }
    }

    /// `OG-05` §7 row 1: every frontier model id AS THE VENDOR'S DOCS PRINT IT
    /// routes to that vendor's own provider row and resolves that vendor's key.
    /// `qwen3.8-max` used to route to GROQ (bare `qwen` claim) — a first-party
    /// Alibaba id sent with Groq's key.
    #[test]
    fn og05_frontier_models_route_to_their_first_party() {
        let table: &[(&str, &str, &str)] = &[
            ("gpt-6-astra", "openai", "OPENAI_API_KEY"),
            ("gpt-6.1-sol", "openai", "OPENAI_API_KEY"),
            ("gpt-6-sol", "openai", "OPENAI_API_KEY"),
            ("gpt-6-luna", "openai", "OPENAI_API_KEY"),
            ("gpt-5.5", "openai", "OPENAI_API_KEY"),
            ("gpt-5.5-pro", "openai", "OPENAI_API_KEY"),
            ("gpt-5.3-codex", "openai", "OPENAI_API_KEY"),
            ("claude-fable-5-1", "anthropic", "ANTHROPIC_API_KEY"),
            ("claude-opus-5-5", "anthropic", "ANTHROPIC_API_KEY"),
            ("claude-sonnet-5-5", "anthropic", "ANTHROPIC_API_KEY"),
            ("claude-haiku-4-5", "anthropic", "ANTHROPIC_API_KEY"),
            ("gemini-3.1-pro-preview", "google", "GOOGLE_API_KEY"),
            ("gemini-3.8-flash", "google", "GOOGLE_API_KEY"),
            ("gemini-3.5-flash", "google", "GOOGLE_API_KEY"),
            ("gemini-3.1-flash-lite", "google", "GOOGLE_API_KEY"),
            ("grok-4.7", "xai", "XAI_API_KEY"),
            ("grok-4.3", "xai", "XAI_API_KEY"),
            ("grok-build-0.1", "xai", "XAI_API_KEY"),
            ("deepseek-flash", "deepseek", "DEEPSEEK_API_KEY"),
            ("deepseek-v4-pro", "deepseek", "DEEPSEEK_API_KEY"),
            ("kimi-k3", "moonshot-intl", "MOONSHOT_API_KEY"),
            ("kimi-k2.6", "moonshot-intl", "MOONSHOT_API_KEY"),
            ("glm-5.3", "zai", "ZHIPU_API_KEY"),
            ("glm-5.3-flash", "zai", "ZHIPU_API_KEY"),
            ("qwen3.8-max", "alibaba", "DASHSCOPE_API_KEY"),
            ("qwen3.7-plus", "alibaba", "DASHSCOPE_API_KEY"),
            ("qwen3.8-flash", "alibaba", "DASHSCOPE_API_KEY"),
            ("qwen-max", "alibaba", "DASHSCOPE_API_KEY"),
            ("mistral-large-3", "mistral", "MISTRAL_API_KEY"),
            ("magistral-medium-2509", "mistral", "MISTRAL_API_KEY"),
            ("codestral-2508", "mistral", "MISTRAL_API_KEY"),
            ("devstral-small-2507", "mistral", "MISTRAL_API_KEY"),
            ("muse-spark", "meta", "META_API_KEY"),
            // Groq keeps ITS namespaced ids.
            ("qwen/qwen3-32b", "groq", "GROQ_API_KEY"),
        ];
        for (model, pid, env) in table {
            assert_eq!(
                ProviderRegistry::provider_id_for_model(model),
                Some(*pid),
                "`{model}` must route to `{pid}`"
            );
            assert_eq!(api_key_env_var(model), Some(*env), "`{model}` key env");
        }
    }

    /// `OG-05`: the guard BLOCKS. Fail-closed is unchanged — an unknown id is
    /// still `None` (so `unroutable_model`), and the bare Groq-era qwen ids that
    /// used to ride the removed `qwen` claim are now unroutable, never
    /// defaulted to some provider's key.
    #[test]
    fn og05_unknown_models_stay_unroutable() {
        for m in [
            "totally-unknown-model-9",
            "kimi",
            "glm5",
            "qwen-2.5-32b",
            "qwen3-32b",
            "muse",
        ] {
            assert_eq!(
                ProviderRegistry::provider_id_for_model(m),
                None,
                "`{m}` must be unroutable (fail-closed), not defaulted"
            );
        }
    }

    /// `OG-05`: the NEW international Moonshot row points at the international
    /// host; the existing China row keeps its host (a re-pointed `base_url`
    /// would send a tenant's key to a host they never chose).
    #[test]
    fn og05_moonshot_international_is_a_new_row_not_a_repoint() {
        let intl = super::catalog::by_id("moonshot-intl").expect("row");
        assert_eq!(intl.base_url_default, "https://api.moonshot.ai");
        let cn = super::catalog::by_id("moonshot").expect("row");
        assert_eq!(cn.base_url_default, "https://api.moonshot.cn");
        assert_eq!(
            super::catalog::by_id("meta").expect("row").base_url_default,
            "https://api.meta.ai"
        );
    }

    /// The Groq arm must NOT steal `llama-3.1-sonar*` — those are Perplexity
    /// and matched earlier in every match (dispatch + both key-lookups).
    #[test]
    fn llama_sonar_still_routes_to_perplexity() {
        let m = "llama-3.1-sonar-large-128k-online";
        assert_eq!(
            ProviderRegistry::provider_id_for_model(m),
            Some("perplexity")
        );
        assert_eq!(api_key_env_var(m), Some("PERPLEXITY_API_KEY"));
    }

    /// Spot-check that the two key-lookup functions stay in lockstep on the
    /// families most likely to drift (the bug was exactly a divergence).
    #[test]
    fn provider_id_and_env_var_agree_on_key_families() {
        let cases = [
            ("claude-sonnet-4-6", "anthropic", "ANTHROPIC_API_KEY"),
            ("gpt-4o", "openai", "OPENAI_API_KEY"),
            ("gemini-2.5-flash", "google", "GOOGLE_API_KEY"),
            ("grok-2", "xai", "XAI_API_KEY"),
            ("llama-3.3-70b-versatile", "groq", "GROQ_API_KEY"),
        ];
        for (model, pid, env) in cases {
            assert_eq!(ProviderRegistry::provider_id_for_model(model), Some(pid));
            assert_eq!(api_key_env_var(model), Some(env));
        }
    }

    /// Coverage audit 2026-07-18: the together/fireworks/openrouter adapters were
    /// registered but UNREACHABLE (no routing prefix → defaulted to anthropic).
    /// They now route via an explicit `provider/` prefix.
    #[test]
    fn aggregator_hosts_are_reachable_via_prefix() {
        for (model, pid, env) in [
            (
                "together/meta-llama/Llama-3.3-70B",
                "together",
                "TOGETHER_API_KEY",
            ),
            ("fireworks/llama-v3p3-70b", "fireworks", "FIREWORKS_API_KEY"),
            (
                "openrouter/anthropic/claude-3.5",
                "openrouter",
                "OPENROUTER_API_KEY",
            ),
        ] {
            assert_eq!(
                ProviderRegistry::provider_id_for_model(model),
                Some(pid),
                "{model} must route to {pid}, not the anthropic default"
            );
            assert_eq!(api_key_env_var(model), Some(env));
        }
    }

    /// Unmatched/bare-name models FAIL CLOSED (None), NOT default to
    /// anthropic. Sending an unknown model to Anthropic with the Anthropic key is
    /// credential misrouting; rejecting is strictly safer. (These are top models
    /// with no bare-name arm — reachable via a provider prefix instead.)
    #[test]
    fn unmatched_models_fail_closed_not_default_anthropic() {
        for model in [
            "kimi", // OG-05: `kimi-` (with the dash) is now moonshot-intl
            "nova-pro",
            "glm4-plus", // OG-05: `glm-` (with the dash) is now zai
            "phi-4",
            "totally-unknown-model-xyz",
            "",
        ] {
            assert_eq!(
                ProviderRegistry::provider_id_for_model(model),
                None,
                "{model:?} must be unroutable (None), never a default provider"
            );
            assert_eq!(
                api_key_env_var(model),
                None,
                "{model:?} must resolve NO key env (never ANTHROPIC_API_KEY)"
            );
        }
        // The prefixed forms route correctly where an adapter exists.
        assert_eq!(
            ProviderRegistry::provider_id_for_model("moonshot/kimi-k2"),
            Some("moonshot")
        );
        assert_eq!(
            ProviderRegistry::provider_id_for_model("bedrock/nova-pro"),
            Some("bedrock")
        );
    }

    /// One representative model per registered provider. Assertion 1 below proves
    /// each routes to its OWN provider, so this list is self-validating.
    const PROVIDER_MODELS: &[(&str, &str)] = &[
        ("anthropic", "claude-sonnet-4-6"),
        ("openai", "gpt-4o"),
        ("google", "gemini-2.5-flash"),
        ("vertex", "vertex/gemini-2.5-pro"),
        ("bedrock", "bedrock/nova-pro"),
        ("azure", "azure/gpt-4o"),
        ("cohere", "command-r-plus"),
        ("mistral", "mistral-large-latest"),
        ("perplexity", "sonar-pro"),
        ("deepseek", "deepseek-chat"),
        ("xai", "grok-2"),
        ("nvidia", "nvidia/llama-3.1-70b"),
        ("cerebras", "cerebras/llama-3.3-70b"),
        ("sambanova", "sambanova/Meta-Llama-3.3-70B"),
        ("lepton", "lepton/llama3-70b"),
        ("lambda", "lambda/llama-3.3-70b"),
        ("novita", "novita/llama-3.3-70b"),
        ("ai21", "jamba-1.5-large"),
        ("hyperbolic", "hyperbolic/llama-3.3-70b"),
        ("deepinfra", "deepinfra/llama-3.3-70b"),
        ("cloudflare", "@cf/meta/llama-3.1-8b"),
        ("ollama", "ollama/llama3.3"),
        ("baseten", "baseten/llama-3.3-70b"),
        ("huggingface", "hf/meta-llama/Llama-3.3-70B"),
        ("anyscale", "anyscale/llama-3.3-70b"),
        ("modal", "modal/llama-3.3-70b"),
        ("predibase", "predibase/llama-3-3-70b"),
        ("moonshot", "moonshot/kimi-k2"),
        ("upstage", "solar-pro"),
        ("yi", "yi-large"),
        ("aleph-alpha", "luminous-supreme"),
        ("groq", "llama-3.3-70b-versatile"),
        ("together", "together/meta-llama/Llama-3.3-70B"),
        ("fireworks", "fireworks/llama-v3p3-70b"),
        ("openrouter", "openrouter/meta-llama/llama-3.3-70b"),
    ];

    ///  cross-leak CI GATE — the mechanical prevention, parameterized over
    /// the FULL provider matrix (N×N, N=35 → 1225 ordered pairs). For every pair
    /// (A, B) with A≠B, calling B's model MUST resolve B's own key env, never A's.
    /// Since the key env is derived from the single canonical
    /// `provider_id_for_model`, this proves at the resolution layer that no
    /// provider's model can fetch another provider's key — the exact
    /// credential-misrouting class cannot silently return. Providers with real
    /// keys are additionally exercised on the wire (see the multi-provider proof);
    /// the rest are asserted-by-construction here.
    #[test]
    fn cross_provider_key_isolation_full_matrix() {
        // 1. Every representative model routes to its OWN provider (self-validating
        //    the list) and yields that provider's key env.
        for (pid, model) in PROVIDER_MODELS {
            assert_eq!(
                ProviderRegistry::provider_id_for_model(model),
                Some(*pid),
                "{model} must route to provider {pid}"
            );
            let env = api_key_env_var(model);
            assert!(env.is_some(), "{model} ({pid}) resolved NO key env");
        }

        // 2. N×N cross-leak: for every ordered pair A≠B, B's model never resolves
        //    A's key env. Distinct non-empty envs ⇒ storing only A's key leaves B's
        //    model with an empty key (upstream 401), never A's key. (ollama's env
        //    is the empty "no key" sentinel — a local, keyless provider.)
        let mut pairs = 0usize;
        for (a_pid, _a_model) in PROVIDER_MODELS {
            let a_env = ProviderRegistry::env_var_for_provider_id(a_pid);
            for (b_pid, b_model) in PROVIDER_MODELS {
                if a_pid == b_pid {
                    continue;
                }
                let b_env = api_key_env_var(b_model).unwrap();
                pairs += 1;
                if a_env.is_empty() || b_env.is_empty() {
                    continue; // ollama carries no key — nothing to leak
                }
                assert_ne!(
                    b_env, a_env,
                    "CROSS-LEAK: model {b_model} (provider {b_pid}) resolves key env \
                     {a_env} which belongs to provider {a_pid}"
                );
            }
        }
        assert_eq!(pairs, PROVIDER_MODELS.len() * (PROVIDER_MODELS.len() - 1));

        // 3. Fail-closed: an unmatched model resolves NO provider and NO key env —
        //    it can never carry ANY provider's credential. (Names chosen to match
        //    NO prefix — note kimi/nova/glm are top models with no bare-name arm.)
        for m in [
            "zzz-nonexistent-model",
            "unknown-xyz",
            "",
            "kimi", // OG-05: `kimi-k2` now routes to moonshot-intl
            "nova-pro",
        ] {
            assert_eq!(
                ProviderRegistry::provider_id_for_model(m),
                None,
                "{m:?} must be unroutable (fail closed)"
            );
            assert_eq!(api_key_env_var(m), None);
        }
    }
}

impl FinishReason {
    /// Gemini's `candidates[].finishReason`.
    ///
    /// Unknown reasons stay absent so the gateway uses its derived default.
    #[must_use]
    pub fn from_gemini_finish_reason(reason: &str) -> Option<Self> {
        match reason {
            "MAX_TOKENS" => Some(Self::Length),
            "SAFETY" | "RECITATION" | "BLOCKLIST" | "PROHIBITED_CONTENT" | "SPII" => {
                Some(Self::ContentFilter)
            }
            "STOP" => Some(Self::Stop),
            _ => None,
        }
    }
}

#[cfg(test)]
mod og03_provider_message_tests {
    use super::{ProviderHttpError, provider_message_from_body};

    const KEY: &str = "unit-test-secret-key-do-not-use-in-prod";

    #[test]
    fn a_relayable_4xx_carries_the_scrubbed_message() {
        let body = r#"{"error":{"message":"Unsupported parameter: max_tokens"}}"#;
        let e = ProviderHttpError::from_response("openai", 400, None, body, KEY);
        assert_eq!(
            e.message.as_deref(),
            Some("Unsupported parameter: max_tokens")
        );
    }

    /// The guard must BLOCK: 401 / 403 / 407 and every 5xx never carry a body, and neither
    /// does a 400 that is a dead key (Google's shape).
    #[test]
    fn nothing_is_relayed_for_auth_statuses_server_errors_or_a_key_400() {
        let body = format!(r#"{{"error":{{"message":"bad key {KEY}"}}}}"#);
        for s in [401u16, 403, 407, 500, 502, 503, 504] {
            let e = ProviderHttpError::from_response("openai", s, None, &body, KEY);
            assert!(e.message.is_none(), "status {s} must not relay a body");
        }
        let e = ProviderHttpError::from_response(
            "google",
            400,
            Some("API_KEY_INVALID".into()),
            &body,
            KEY,
        );
        assert!(e.message.is_none(), "a dead-key 400 must not relay a body");
    }

    #[test]
    fn the_tenants_own_key_and_key_shapes_are_removed_and_the_text_is_bounded() {
        let body = format!(
            r#"{{"message":"model rejected key {KEY} and sk-proj-abcdefghijklmnopqrstuvwxyz0123"}}"#
        );
        let m = provider_message_from_body(&body, KEY, 512).expect("message");
        assert!(!m.contains(KEY), "{m}");
        assert!(!m.contains("sk-proj-"), "{m}");
        let long = format!(r#"{{"error":{{"message":"{}"}}}}"#, "x".repeat(2000));
        let m = provider_message_from_body(&long, KEY, 512).expect("message");
        assert_eq!(m.chars().count(), 512);
        assert!(m.ends_with('…'));
        // Fail-closed: a zero cap (an unparseable policy table) relays nothing.
        assert!(provider_message_from_body(&long, KEY, 0).is_none());
        // Every body shape the adapters meet: xAI / Cohere / Bedrock string forms.
        assert_eq!(
            provider_message_from_body(r#"{"error":"Bad request shape"}"#, KEY, 512).as_deref(),
            Some("Bad request shape")
        );
        assert!(provider_message_from_body("not json", KEY, 512).is_none());
    }
}
